### ISSUE TITLE
ENTSO-E API not working on ESP8266? 

### ISSUE THREAD

**Issue by ArnieO** [gskjold/AmsToMqttBridge#106]
I just flashed an ESP-12, and the device says:
_"There is currently not enough available heap space on your device to support this feature. If you are using ESP8266, you can consider switching to ESP32 to get enable this feature"_

If this is as expected it would be great if we could inform on the device requirements in the Wiki!

**Comment by gskjold** [comment]
Done
https://github.com/gskjold/AmsToMqttBridge/wiki/Configure-EntsoE-API
