### ISSUE TITLE
Wiki improvement proposition: Documentation of */data.json

### ISSUE THREAD

**Issue by ArnieO** [gskjold/AmsToMqttBridge#107]
It would be great to have a list showing what each of the values returned by */data.json are.
Some are evident, but not all:
![image](https://user-images.githubusercontent.com/10295178/123163652-3ece4d80-d472-11eb-9c9a-08c232ed0be5.png)

**Comment by gskjold** [comment]
https://github.com/gskjold/AmsToMqttBridge/wiki/Message-formats
