### ISSUE TITLE
Unit starts with debugging enabled

### ISSUE THREAD

**Issue by ArnieO** [gskjold/AmsToMqttBridge#109]
Hardware: Pow-U 
Hardware setting:
![image](https://user-images.githubusercontent.com/10295178/123398220-8e606680-d5a3-11eb-8d41-db96c10945bb.png)

After restart, the debugging is active:
![image](https://user-images.githubusercontent.com/10295178/123398456-daaba680-d5a3-11eb-9087-6c7535d3808e.png)

I assume debugging should not be active by default; could cause conflict on units using UART0 Rx pin as HAN-input.

**Comment by gskjold** [comment]
Are you sure this is not a residual config from earlier? I am unable to reproduce on a blank board.

**Comment by ArnieO** [comment]
It is systematic. For each new blank board I program those two are set when I enter the debug menu.

**Comment by gskjold** [comment]
Reproduced with brand new board
