### ISSUE TITLE
Suggestion: Rename Kamstrup meter types in "Meter" dropdown list 

### ISSUE THREAD

**Issue by ArnieO** [gskjold/AmsToMqttBridge#112]
All Kamstrup AMS meters are named Kamstrup Omnipower, whether they encrypt the HAN port or not. And I learned today that some Kamstrup AMS meters in Denmark are not encrypted, so country should not be used as tag. 

I propose to rename the two versions as:
- **Kamstrup non-encrypted**
- **Kamstrup encrypted**

**Comment by gskjold** [comment]
Agreed, change commited.
