### ISSUE TITLE
Wrong value for accumulated active export energy

### ISSUE THREAD

**Issue by ArnieO** [gskjold/AmsToMqttBridge#114]
I read identical figures for accumulated active and accumulated reactive export:
![image](https://user-images.githubusercontent.com/10295178/133753925-435f9bc0-25c9-4d4c-8f1a-093c5e817b46.png)

The total accumulated export from my installation is much lower than 14150 kWh, so that figure is definitively incorrect. 

JSON:
![image](https://user-images.githubusercontent.com/10295178/133754764-def0530d-0b22-4513-b6f5-a213035f21da.png)

I checked the display on the meter, and found:
- ic: Correct
- ec: Wrong, meter shows 4526 kWh, and this figure is not in the JSON list
- ric: Correct
- rec: Correct

So I think there is a copy/paste error on the 'ec' figure, the displayed value is 'rec'.

**Comment by gskjold** [comment]
Good catch, commited a fix for next release
