### ISSUE TITLE
Kindly add HW profiles for Pow-U / Pow-K

### ISSUE THREAD

**Issue by ArnieO** [gskjold/AmsToMqttBridge#118]
Kindly add two new HW profiles:

- Pow-U or Pow-K from amsleser.no (UART0)
- Pow-U or Pow-K from amsleser.no (GPIO12)

Same HW profile as the current "Kamstrup module by Egil Opsahl", except for HAN pin.

**Comment by gskjold** [comment]
Added:
https://github.com/gskjold/AmsToMqttBridge/blob/867d6a4ef8e6013395ce78a31ceead198b658d11/src/web/AmsWebServer.cpp#L767
