### ISSUE TITLE
Suggestion: Remove "Temperature" and "Energy Price" menus for devices that cannot display them

### ISSUE THREAD

**Issue by ArnieO** [gskjold/AmsToMqttBridge#120]
If not too complicated to implement, these two menu items could be omitted:
- Omit "Temperature" on devices that do not have temp sensor 
- Omit "Energy Price" on ESP8266-based devices

![image](https://user-images.githubusercontent.com/10295178/134330701-c7fc7eb9-23d1-49fb-a184-dad1205563c8.png)
![image](https://user-images.githubusercontent.com/10295178/134330736-e0de9695-917e-4a5a-a206-d53a4d0bbcfc.png)

**Comment by gskjold** [comment]
This is actually a bit harder than one would believe, mostly because the most likely solutions would waste either runtime memory or flash space, which are both stretched in this project for different reasons.

**Comment by ArnieO** [comment]
Telnet log indicates that the unit spends around 750 ms trying to read temp on a unit with no temp sensor. Not knowing those details of the code, I imagined it could be possible to «if» around it by testing the setting on the GPIO screen. But if simple solution impossible, we live well with «as is»!

**Comment by gskjold** [comment]
It already check if GPIO is set, so it will not query sensors if no GPIO is set.

The "hard part" would be to remove the menu items, as they are hard coded for memory optimization.

**Comment by gskjold** [comment]
Found a suitable solution for this, added for next major version
