### ISSUE TITLE
How to convert meter and package timestamps?

### ISSUE THREAD

**Issue by madsbg** [gskjold/AmsToMqttBridge#130]
When I try to convert the meter (data.rtc) and package (t) timestamps, I get a date 23 days in the future.

My current local time in Denmark is 2021-10-15 13:25:00

The timestamp I have received via MQTT is 1636266670
According to www.unixtimestamp.com that translates to 2021-11-07 06:31:10

The data from the meter is correct (from earlier today):
```
0  7E5 0A 0F 05 0A 11 00 FF 80 00 80
  2021-10-15    10:17:00
```

Is that a bug or am I doing something wrong?

________
_Edit: spelling_

**Comment by gskjold** [comment]
@ArnieO could you verify if you have a similar problem?

**Comment by madsbg** [comment]
As expected, my meter's timestamp did not change time zone today. It is still sending timestamps in CET time, which is now the current time zone here in Denmark. For anyone interested, I use this simple template in Home Assistant to adjust the meter's timestamp according to daylight savings time:

```
value_template: >
  {% if now().timetuple().tm_isdst == 0 %}
    {{ value | int | timestamp_local }}
  {% else %}
    {{ (value | int - 3600) | timestamp_local }}
  {% endif %}
```
