### ISSUE TITLE
Update wiki

### ISSUE THREAD

**Issue by gskjold** [gskjold/AmsToMqttBridge#149]
- [x] Better description of flashing for ESP32, specifically in Windows.

**Comment by gskjold** [comment]
Also, add info about voltage sensing on ESP32.
At the same time, write about D1 mini, NodeMCU and others that have a voltage divider attached to ADC that disturbs the reading on ESP8266

**Comment by gskjold** [comment]
- [ ] Update readme and screenshot
- [ ] Add some images and explanation about the dashboard in a page in the wiki

**Comment by ArnieO** [comment]
While you're at it:

- This page needs updating: https://github.com/gskjold/AmsToMqttBridge/wiki/Meter-configuration
- This page is empty: https://github.com/gskjold/AmsToMqttBridge/wiki/Threshold-configuration
