### ISSUE TITLE
Setup instructions

### ISSUE THREAD

**Issue by 1v4r** [gskjold/AmsToMqttBridge#15]
Hi. I tried to find some instructions on how to set this up. After flashing the image to an ESP8266 and rebooting it I detect the ESP wifi for a short period but I'm unable to connect to it. I tried to look for more instructions here and on @roarfred's repo but I was not able to find any more info.

**Comment by gskjold** [comment]
Then there may be a problem in the code, causing it to reboot. What hardware are you using? And is it connected to the meters HAN port when this happens?

**Comment by gskjold** [comment]
Tested with a clean board and got an error. Attached is a new firmware file.
[firmware.zip](https://github.com/gskjold/AmsToMqttBridge/files/4143650/firmware.zip)

**Comment by gskjold** [comment]
Assuming this was resolved
