### ISSUE TITLE
Error saving configuration

### ISSUE THREAD

**Issue by manfi001** [gskjold/AmsToMqttBridge#152]
Flashed firmware to a ESP07 with ESP-Flasher
device starts in AP mode after reboot but when trying to save initial configuration, I get error msg: Error saving configuration!
what could be wrong?
 - M-bus adapter: TSS721

**Relevant firmware information:**
 - Version: [e.g. 1.5.8]
 - MQTT: [yes/no]
 - HAN GPIO: [not yet connected ]
 - Temperature sensors [none]

**Comment by gskjold** [comment]
Sorry, but the project has been built with a 4MB partition layout which overflows the 1MB memory chip on ESP07

**Comment by manfi001** [comment]
Thanks for info.
Flashed to D1mini and o.k.
Trying to use it in Austria with a Sagemcom T210-D smart-meter.
Will get the decryption keys shortly and let you know how it works.
br

**Comment by gskjold** [comment]
Awesome! Let me know how that works out, I would really like to get this working for as many meters as possible.

**Comment by gskjold** [comment]
By the way, your meter will only be supported by the 2.0 series firmware we are currently testing in #143

**Comment by manfi001** [comment]
Hi Gunnar,If you are interested, I could send you the documentation about the meter interface of my electricity provider. however it is in GermanbrSent from my Tablet
-------- Original message --------From: Gunnar Skjold ***@***.***> Date: 12/4/21  14:52  (GMT+01:00) To: gskjold/AmsToMqttBridge ***@***.***> Cc: manfi001 ***@***.***>, State change ***@***.***> Subject: Re: [gskjold/AmsToMqttBridge] Error saving configuration (Issue #152) 
By the way, your meter will only be supported by the 2.0 series firmware we are currently testing in #143

**Comment by gskjold** [comment]
Thanks but I have found some information on it already. It uses ESMR 5.0, which technically should work with v2.0.
