### ISSUE TITLE
Power factor not included in MQTT 

### ISSUE THREAD

**Issue by henriklund** [gskjold/AmsToMqttBridge#162]
Super stuff done on the new v2.0.0!!!

I can see that PowerFactor is now included in the JSON. However, when querying MQTT it does not appear to be included.

Deployed version is ams2mqtt-esp8266-2.0.0.bin on a Pow-K module.

**Comment by henriklund** [comment]
Duly noted. I will look forward to 2.0.2 then :)

**Comment by madsbg** [comment]
What is power factor and how do I know if my meter supports it?

I use MQTT Raw (full) format, and I receive {root}/meter/powerfactor and {root}/meter/l1/powerfactor, which both have a value of zero, but neither {root}/meter/l2/powerfactor nor {root}/meter/l3/powerfactor are present.

**Comment by henriklund** [comment]
You can read about power factor [here](https://www.fluke.com/en/learn/blog/power-quality/power-factor-formula). As for whether your meter is supported, I guess it might depend on model. Mine is the Kamstrup Omnipower [DIN rail](https://www.kamstrup.com/en-en/electricity-solutions/meters-devices) version.

Do you get the same results if you query http://meter-ip/data.json? (look for the f + f1-f3 values).

**Comment by madsbg** [comment]
I have the Kamstrup Omnipower three-phase meter (Denmark/SEAS-NVE).

data.json:
![data_json](https://user-images.githubusercontent.com/73168571/145987871-d2d93afd-2578-4f3c-8fda-133025f523ab.png)

MQTT:
![mqtt](https://user-images.githubusercontent.com/73168571/145987887-46d71fa9-d568-44bb-9263-9dd8f9f84632.png)

**Comment by henriklund** [comment]
My guess is that it is either a bug (@gskjold could elaborate here) that causes data not to get loaded from meter or that your meter might not have the firmware necessary for this (see the link in [this post](https://github.com/gskjold/AmsToMqttBridge/issues/136)).

**Comment by madsbg** [comment]
Thanks. What does your data.json look like?

**Comment by henriklund** [comment]
Redacted some irrelevant info:
![image](https://user-images.githubusercontent.com/8402745/146029955-ac186af0-99c0-429e-a001-81a7ee334b18.png)

**Comment by gskjold** [comment]
#163 will at least fix what is missing in MQTT raw

**Comment by gskjold** [comment]
Commited fix
