### ISSUE TITLE
Sweden use main fuses of size 16A and 20A

### ISSUE THREAD

**Issue by ArnieO** [gskjold/AmsToMqttBridge#164]
Some installations in Sweden have main fuses 16A and 20A.

A user in Sweden requests this to be added to the list of possible main fuse values:

![image](https://user-images.githubusercontent.com/10295178/146441824-c0e2f088-be28-43d7-8aee-8b970e47e0a4.png)

**Comment by gskjold** [comment]
Already added in 2.0
