### ISSUE TITLE
Missing tPI value in MQTT-message

### ISSUE THREAD

**Issue by thrawnarn** [gskjold/AmsToMqttBridge#165]
I'm missing the tPI value in my json mqtt-message. And I can see in the wiki that there is 3 kinds of lists in the mqtt message. How do I choose which to publish?

https://github.com/gskjold/AmsToMqttBridge/wiki/Message-formats

**Comment by gskjold** [comment]
The different lists are based on what the meter provides. Please provide country and meter model.

**Comment by thrawnarn** [comment]
I live in Sweden and has a Kamstrup meter. Do you need to know the exakt model?

**Comment by thrawnarn** [comment]
I can see the values in the web-interface

![bild](https://user-images.githubusercontent.com/5276026/146611584-9dc9cc82-c197-4db8-82d6-239622ee095d.png)

**Comment by gskjold** [comment]
Not sure how it is with swedish kamstrup. If it uses the norwegiam standard (as some swedish meters do), you will only receive list3 once every hour.

**Comment by thrawnarn** [comment]
hmm, ok. I think mine is using the norwegian standard. Then I will wait an hour to see if it updates :)
Thanks

**Comment by gskjold** [comment]
No problem. You should get it approx 23.00.10

**Comment by thrawnarn** [comment]
FYI: I've confirmed it in Home Assistant now, I could see it in the history. Now I will have to find a way around this... But thats tomorrows problem.

**Comment by gskjold** [comment]
Yeah, pretty inconvenient... I calculate an real time estimate in openhab based on current active import and time since last message. It is not exact, but good enough for me. Same estimate calculation is used on accumulated values in gui. You will see they get corrected (forward or backward) when you receive list 3
