### ISSUE TITLE
v2.0.2 minor issues

### ISSUE THREAD

**Issue by ArnieO** [gskjold/AmsToMqttBridge#171]
**Describe the bug**

1. When upgrading from 2.0.1,  daily consumption historic was lost (hourly not lost)
2. The clock is not correct:
![image](https://user-images.githubusercontent.com/10295178/146751596-4cd3461c-9a3f-44b5-8e21-3a624fc80214.png)
Current date/time: 20th December 2021, 11:18

**Hardware information:**
 - Meter: Kamstrup
 - Pow-K

**Relevant firmware information:**
 - Version: 2.0.2
 - MQTT: No
 - HAN GPIO: UART0
 - Temperature sensors: No

**Comment by gskjold** [comment]
Thanks, that's interesting. I will look in to what may cause month graph to be cleared. I'm guessing it is related to the clock,

Judging by the timestamp your device have been up for 12 minutes at that point and should have been updated. It suggests that NTP does not work, either because of configuration (NTP config or missing DNS in IP config) or firewall.

If NTP is not possible in your setup, the clock will synchronise with meter timestamp at next hourly update.

**Comment by ArnieO** [comment]
I'm in a new home and wifi conditions are not good (many other things to take fix...). Maybe that could cause the NTP issue?

But after two hours the clock is still not synchronized:
![image](https://user-images.githubusercontent.com/10295178/146766455-c85f447c-2929-47da-8dd7-1150ba004eea.png)
![image](https://user-images.githubusercontent.com/10295178/146766571-2e5507ef-7227-491e-a25f-1af2b26122f7.png)

**Comment by ArnieO** [comment]
Correction: 
When I lost daily values I did not upgrade from 2.0.1 but from 2.0-rc4.
That may explain it.

**Comment by gskjold** [comment]
Ah yes, there was a problem with the earlier rc of 2.0

**Comment by ArnieO** [comment]
The clock seems to run, but the date is stuck. 
![image](https://user-images.githubusercontent.com/10295178/146891719-517b434c-c3b9-473d-b70e-b708e462e248.png)

**Comment by bardahlm** [comment]
Can the timestamps from the meter be used if NTP is not working?

**Comment by gskjold** [comment]
It should use meter timestamp if NTP is not available. There must be something wrong since that doesn't happen

**Comment by gskjold** [comment]
@ArnieO could you screenshot your ntp config page and ip config page? Also, are you using static IP? If so, what DNS have you configured?

**Comment by ArnieO** [comment]
I have not specified DNS, as my understanding was that it is only needed for SSL. Wrong?

![image](https://user-images.githubusercontent.com/10295178/146999395-05031f90-18bd-4749-b7aa-2349d2df183b.png)
![image](https://user-images.githubusercontent.com/10295178/146999429-fce35a0a-d38c-4d78-8dd6-32fdbebaf839.png)

**Comment by gskjold** [comment]
Needed for NTP and ENTSO-E to work. It is unable to look up pool.ntp.org

I have also found out why it doesn't use meter time

**Comment by gskjold** [comment]
> my understanding was that it is only needed for SSL. Wrong?

Not entirely untrue. DNS is needed for SSL because SSL requires a synchronized clock which we would need to get from NTP. Meter timestamp would of course also work, but then you have to wait for the next hourly update before it works.
