### ISSUE TITLE
Example ini file refers to non-existent element in common

### ISSUE THREAD

**Issue by Jendem** [gskjold/AmsToMqttBridge#176]
Example ini file refers to non-existent `${common.framework}`. Removed in 74bc5aa7a02a9015241574f24e3b6afb3f11b30e

https://github.com/gskjold/AmsToMqttBridge/blob/ff02dd43a91c6b3b129eef0004b53e959c7ed4d0/platformio-user.ini-example#L7

**Comment by gskjold** [comment]
Thanks!
