### ISSUE TITLE
mqtt: Increase number of decimals on /meter/import/active/accumulated

### ISSUE THREAD

**Issue by eivindsl** [gskjold/AmsToMqttBridge#177]
The accumulated values have currently 2 decimals, while the consumption reported to Elhub contains 3 decimals.
If the resolution of the raw value from MBus allows, increasing number of decimals to 3 or 4 would give more exact values for price estimation.

**Comment by gskjold** [comment]
Increasing to 3 decimals. I don't think any meter I know of report more than that.
