### ISSUE TITLE
"New" Dark mode in Chrome

### ISSUE THREAD

**Issue by hanseinar** [gskjold/AmsToMqttBridge#179]
The color scheme is not ideal for dark mode. The text in the gauge is hardly readable. 

Perhaps it is possible to find a color combination that handle both light and dark mode in a good way
![1](https://user-images.githubusercontent.com/8856635/147852834-978339fc-8979-4c15-8a0d-4cd82b914a4c.png)
.

**Comment by gskjold** [comment]
Question, how do I enable dark mode in chrome?

**Comment by hanseinar** [comment]
Paste:
chrome://flags/#enable-force-dark
in addr field and hit enter

**Comment by gskjold** [comment]
I am not so sure that a forced stylesheet is something we should support at all, but I can have a look at some point if there is a simple solution to it.

**Comment by gskjold** [comment]
Added transparent background on graphs helps a lot. Added for 2.0.3
