### ISSUE TITLE
Missing tick mark on configuration MQTT "enable" box

### ISSUE THREAD

**Issue by ArnieO** [gskjold/AmsToMqttBridge#18]
When clicking the tick mark box, the entry of parameters is enabled, but the "Enable" tick mark or button does not change.

**Comment by gskjold** [comment]
Could you elaborate on this? Maybe add a screenshot

**Comment by ArnieO** [comment]
OK, I see now that this is browser-dependent. 
In Chrome (on Win10) it looks fine, but in Firefox (on Win10) there is no tickmark. 

Firefox:
![image](https://user-images.githubusercontent.com/10295178/74060158-aa348e00-49e9-11ea-9d63-9cd14514bfa6.png)

Chrome:
![image](https://user-images.githubusercontent.com/10295178/74060210-c6d0c600-49e9-11ea-9c26-d34e15336a1a.png)

**Comment by gskjold** [comment]
Incorrect styles set in internal css. Fixed
