### ISSUE TITLE
Show decrypted data in debug output

### ISSUE THREAD

**Issue by madsbg** [gskjold/AmsToMqttBridge#186]
In earlier firmware versions, the decrypted frame data was shown in the debug output. Could you please enabled that again?

```
(D) (HanReader)Data after decryption:
(D) ...
```

**Comment by gskjold** [comment]
The payload you get in the output after v2.0.0 is the decrypted payload. Because of my choices on how to parse and decrypt the frames in my new decoder, this is how it will be from now on.
