### ISSUE TITLE
User selectable telnet debug session inactivity timeout

### ISSUE THREAD

**Issue by madsbg** [gskjold/AmsToMqttBridge#187]
Would it be possible to make the telnet debug session timeout user adjustable? The current timeout seems to be 10 minutes. I would like to be able to increase that to at least a couple of hours for easier unattended logging.

**Comment by gskjold** [comment]
Not supported by upstream library. https://github.com/JoaoLopesF/RemoteDebug

I see the telnet debugger as a tool to help me (as the maintainer), and is not really a user feature. Chances are I will remove the debugger in the future as it is cause for just as many bugs as it helps fix.
