### ISSUE TITLE
Unused `config.meterType` in `AmsWebServer.cpp`

### ISSUE THREAD

**Issue by Jendem** [gskjold/AmsToMqttBridge#193]
There is no meter type in setup html. 

https://github.com/gskjold/AmsToMqttBridge/blob/9897ccc56390da4429b66e498f69a15af5a74287/src/web/AmsWebServer.cpp#L325-L327

Meter type was removed in 181fe3c909afa66b9da2237d04bfe2e5369c3cac

**Comment by gskjold** [comment]
Thanks!
