### ISSUE TITLE
Kamstrup meter, Denmark, incorrect Current readout

### ISSUE THREAD

**Issue by GGBMLC** [gskjold/AmsToMqttBridge#194]
Hi 
I happy that my setup now works. But I found one mysterious with the current data. 

Step to reproduce the issue:

Note down the total power “watt” and  Phase current for L1, L2 and L3. 
I read the data from the web browser. 
Be sure not any other change of the consumption. 

I use a “about” 2000 watt heater for testing. 

In my case:
373 watt Import
L1: 1,74A
L2: 0,6 A
L3: 0,4 A

Then connect a consumption of a load of 2000 watt “10 A” on L1. 
2,3 kW Import
L1: 9,3 A
L2: 6,8 A (the current rises here ?)
L3: 0,4 A
This is total 3795 watt?  But the meter shows 2,3kW?

Then connect a consumption of a load of 2000 watt “10 A” on L2. 

Phase L2 is fine. 

2,3 kW Import2
L1: 1,74A
L2: 8,3 A
L3: 0,4 A
Total watt ok.

Then connect a consumption of a load of 2000 watt “10 A” on L3. 
2,3kw Import
L1: 1,74 A
L2: 7,02 A (the current rises here ?)
L3: 8,3 A 
This is total 3923 watt?  But the meter shows 2,3kW?

Bug: 
1:
The total power does not match the total power delivered from each Phase. 
W=(V1 X L1A)+ (V2 X L2A)+ (V3 X L3A)

2:
Some of load on one single phase (L1 pr L3) is also showed on another phase “L2”. 

Note:
Load on L2 is ok. I can also not guarantee, that the phase can be switched in my installation. "L1 and L3"

Sorry but I don't know if that’s an error in the Kamstrup sw, or in the AmstToMqttBridge sw.

I tried the cases several time to be sure about the issue. 

Hardware information:
•	Meter: Kamstrup, 3F, Denmark
•	AMS reader: Wireless module ESP8266-NodeMcu v3 CH340.
•	M-bus adapter (if applicable):

Relevant firmware information:
•	Version: v2.02
•	MQTT: [yes/no] , Yes
•	HAN GPIO: GPIO13
•	Temperature sensors, Not used/tested

**Comment by ArnieO** [comment]
The short answer is that you cannot calculate 3-phase like you indicate, as the voltages and currents are phase shifted.
As far as I can see, what you experience is "as expected". 

Please google 3-phase systems to learn more.

**Comment by GGBMLC** [comment]
Why is the current so measured ok on only one of the phases?
I know how the meter works,, and how the 3 phase system work (120 deg between phase).

**Comment by tronde-ams** [comment]
Have you in some way configured your meter as 230V IT? Config - meter - distribution system. Denmark is as far as I know only using 400V TN. Or do you have a combination of both 400V and 230V loads active at the same time? 

Does the Danish meter have a menu showing different values? Most (all?) Norwegian meters have a user accessible menu by means of a push-button.

**Comment by GGBMLC** [comment]
The meter is set to TN (400V).
The only 3 fase is the oven. All other are single phase.
Yes the meter has a menu there can be selected by a button.

**Comment by tronde-ams** [comment]
Compare the values from the meter and the WEB-interface. It might give a clue about the problem. 

We Norweginans must be very aware of the differences between IT and TN, since we ar most familiar with the "wacky" IT system. Single phase 230V load in TN is a real single phase load, as opposed to "our" 230V IT-system.

**Comment by gskjold** [comment]
Selection of IT or TN in the menu has no effect on values other than maximum value for the graph.

The software applies a calculation for L2 current for IT/TT meters that does not report this value on the HAN port, but it should not be applied for your meter considering you are in Denmark and all values are reported on HAN port.

Compare values from meter with values in web interface as suggested above and let me know if it does not match.

**Comment by GGBMLC** [comment]
I do some more investigation.
Tried to measure the current with my Fluke meter and compare data from the AMS reader.

10A load on one phase. (230V).
The current load increases exact on each phase. But load on L1 and L3 give
![kamstrup log 20220111](https://user-images.githubusercontent.com/92221040/149017997-10e5cefb-197f-40b0-bd1d-74419717dce6.PNG)
s an error load extra on L2 with about 7.4A
Load on L2 there is no error.
![kamstrup log 20220111](https://user-images.githubusercontent.com/92221040/149017660-2c035104-ac59-41d5-b2bd-5b2d754e8169.PNG)

I also check the data with Telnet. For mee is look fine.
My meter does not support the function for check current in the display.

**Comment by GGBMLC** [comment]
I do some more investigation.
Tried to measure the current with my Fluke meter and compare data from the AMS reader.

10A load on one phase. (230V).
The current load increases exact on each phase. 
But load on L1 and L3 gives an error load extra on L2 with about 7.4A
Load on L2 there is no error.

I also check the data with Telnet. For mee is look fine.
My meter does not support the function for check current in the display.

![kamstrup log 20220111](https://user-images.githubusercontent.com/92221040/149018378-46b22c13-9b92-4496-a625-1156dd0706d3.PNG)

**Comment by gskjold** [comment]
Reading L1=5.29 L2=12.44 L3=1.16 from your screenshot. Are these the same values shown in gui?

**Comment by gskjold** [comment]
Same error with v2.0.3?

**Comment by GGBMLC** [comment]
HI
Version 2.0.3 
Only 2 phase ?

![ams reader v2_0_3](https://user-images.githubusercontent.com/92221040/149381501-5187d0b3-f1f7-4a6d-92bd-416edf9832a6.PNG)

**Comment by gskjold** [comment]
Interesting, your payload has value for all phases.. But this explains why you had incorrect value for L2 current earlier, because in 2.0.2 it would calculate 0-value, but in 2.0.3 you have to select IT/TT system in meter config to enable calculation for L2.

Cant really tell why L2 current would disappear like that. Could you enable verbose level debug and send me a few frames?

**Comment by gskjold** [comment]
If you are already using GPIO13, you should have HAN pin set to UART2 which is a hardware serial pin swap from pin 3 to pin 13.

**Comment by GGBMLC** [comment]
system setting to GPIO13 then AMS reader is not connected to the meter.

Error with boundry flag missing.

The data package also not end with "7E
[UART2F.txt](https://github.com/gskjold/AmsToMqttBridge/files/7871751/UART2F.txt)
"

**Comment by ArnieO** [comment]
Did you try using UART2 (not GPIO13) in the setting?
![image](https://user-images.githubusercontent.com/10295178/149551164-b555b469-6f41-451d-818a-986b70e6f983.png)

**Comment by GGBMLC** [comment]
Hi 
Last log is with settings UART2 (GPIO13) setting. 
But then I do not get any data from the meter.

**Comment by GGBMLC** [comment]
Note. The wiki do not have any information about HW setup for the ESP8266-NodeMcu v3 CH340 board. 
Suggest to add a "whitelist" of ESP boards there works with this nice setup. 
I start with a D1 Mini but never get this board to work with my meter. 
See Issue "https://github.com/gskjold/AmsToMqttBridge/issues/173"

Then order a new ESP8266 board. 

Now I use this one:
https://www.myarduino.dk/produkt/wireless-module-esp8266-nodemcu-v3-ch340/

**Comment by ArnieO** [comment]
This looks like read error, I suspect a hardware issue. 
How do you connect to the meter? 
Photo could be helpful.
Others have reported connectivity issues using Dupont-type wires. 
Could also be power issues on the NodeMCU (potential voltage instability), if I'm allowed to speculate.
Are you powering your board from the 6-pin connector in the meter? If so, the voltage regulator (in the NodeMCU?) needs to have low enough dropout to handle 4,15V.

**Comment by GGBMLC** [comment]
I now tried with new Dupont wire.
Setting, Pin
GPRIO 13, D7,. no data
GPRIO 16, D0, no data
GPIO 03, RX, no data
GPIO 04, D2, no data
GPIO 13, D7,data but then missing data from one phase
GPIO UART2, D7 no data

**Comment by GGBMLC** [comment]
![20220118_211228](https://user-images.githubusercontent.com/92221040/150011818-22cb3fe7-2f98-4878-a4cd-81120450b8f5.jpg)
![20220118_211419](https://user-images.githubusercontent.com/9222104
![20220118_211401](https://user-images.githubusercontent.com/92221040/150012017-8161c7e2-8589-49a1-beff-89336b54e672.jpg)
0/150011988-f211a04f-2a9d-4246-bcd5-897cfe8f1d3f.jpg)

**Comment by ArnieO** [comment]
Thanks! 

1. I would suspect that power supply for this application. Try a beefier one, or a power bank.

2. Try adding large, low-ESR capacitor to 3,3V on the board - as close as possible to the ESP.

**Comment by GGBMLC** [comment]
The power supply is a 5V, 2A. The board do not use 2A.  (10w). 

I assume the ESP8266 PCB/schematic include DC capacitor. 

But of course this kind of high speed electronics require stable DC supply.

**Comment by ArnieO** [comment]
The photo is blurry, but... are you on the bottom two pins here?
![image](https://user-images.githubusercontent.com/10295178/150743326-0c41cec8-cfc5-460c-9f37-0c010ad6efd8.png)
Data_Out is on the middle top pin, see https://github.com/ArnieO/SmartMeterDocumentation#han-interface-description

**Comment by GGBMLC** [comment]
![kamstrup](https://user-images.githubusercontent.com/92221040/151042929-ceb18bf5-2c3b-4543-916e-235d43de36ef.PNG)
connected to GND and DATA out.

**Comment by ArnieO** [comment]
OK, I have read the thread and looked at your logs again.

To summarize (please correct me if this is wrong!):
- You receive **valid** data with HAN set to GPIO13 - but L2 current is missing
- You receive **invalid** data with HAN set to UART2(GPIO13)

@gskjold --> Any idea after looking at the logs (https://github.com/gskjold/AmsToMqttBridge/issues/194#issuecomment-1015523454)?

**Comment by gskjold** [comment]
Not sure why UART2 would be worse than GPIO13... And L2 should not be missing on danish kamstrup. Try the attached firmware and see if there is any difference

[esp32.zip](https://github.com/gskjold/AmsToMqttBridge/files/7960555/esp32.zip)
[esp8266.zip](https://github.com/gskjold/AmsToMqttBridge/files/7960556/esp8266.zip)

**Comment by GGBMLC** [comment]
![telnet log](https://user-images.githubusercontent.com/92221040/151605758-cfdefb4b-9f24-4759-b3f9-fba35022f571.PNG)
![ams reader 220128_1](https://user-images.githubusercontent.com/92221040/151605768-29188f17-8e95-4455-83b2-b8589365cc1d.PNG)
Hi
I tried with my ESP8266 board. GPIO setting: UART2 (GPIO13).
The meter show data but still the L2 is missing. 
I was not able to set my Telnet to save the logfile. Will try later.

**Comment by gskjold** [comment]
I have made some adjustments that I hope will work, try the attached firmware:
[esp32.zip](https://github.com/gskjold/AmsToMqttBridge/files/8000761/esp32.zip)
[esp8266.zip](https://github.com/gskjold/AmsToMqttBridge/files/8000762/esp8266.zip)

**Comment by GGBMLC** [comment]
![20220204](https://user-images.githubusercontent.com/92221040/152492540-59f90244-b966-4249-b9ec-5915b3d2cc27.PNG)
GPIO setting : UART2(GPIO13)
Firmware 220204.1
Then I not getting any data.

**Comment by ArnieO** [comment]
Check that you parity is set correctly (Configuration/Meter)

**Comment by GGBMLC** [comment]
Hi. I check the meter setting. Sorry, but it was not set to 8N1.
Great news. All 3 phases is now pressent. 

![20220204_meter](https://user-images.githubusercontent.com/92221040/152498368-26c07e85-6800-46f4-bb5a-e180c584313f.PNG)

**Comment by gskjold** [comment]
Excellent!
