### ISSUE TITLE
Missing data?

### ISSUE THREAD

**Issue by stigvi** [gskjold/AmsToMqttBridge#195]
**Describe your problem**
I didn't received data from meter/import/active/accumulated at midnight today with the 2.0.3 version. All the other 23 hours are fine. Is it only a coincidence or have someone else experienced the same?

<img width="290" alt="image" src="https://user-images.githubusercontent.com/25978315/148900690-244cfa7c-779e-4e0b-b60a-c93dd30bbc24.png">

<img width="739" alt="image" src="https://user-images.githubusercontent.com/25978315/148901081-95d33b51-0758-4e9a-b9f9-d308262298cd.png">

**Hardware information:**
 - Meter: Aidon
 - AMS reader: ESP32

**Relevant firmware information:**
 - Version: 2.0.3
 - MQTT: yes

**Comment by Isaksson** [comment]
I am using version 2.0.3 for ESP8266 and I do not have that issue.
![image](https://user-images.githubusercontent.com/4119080/148907444-2b18d9ea-7b9a-44f9-b0a5-3e3a3b9de27c.png)

**Comment by ujhede** [comment]
I am using an ESP32 and have data for all hours in the chart.

You guys are burning some serious kWh's,  does not look like EV charging - electric heating ?

**Comment by Isaksson** [comment]
Nope, no heating just several computers and  electrical equipment (and an old electrical ventilation system that i will replace) 🙂

**Comment by gskjold** [comment]
Sometimes there is a checksum error and data is lost, there isn't really much to do about that. How have the last couple of days been @stigvi ?
