### ISSUE TITLE
Does ENTSO api currency conversion work ?

### ISSUE THREAD

**Issue by ujhede** [gskjold/AmsToMqttBridge#197]
I have set Currency to DKK but numbers sent via MQTT looks to be prices in EUR.

BTW!  This is simply the coolest piece of Software written for any Micro controller.  thanks and keep up the fantastic work

**Hardware information:**
 - Meter: Kamstrup Danish
 - AMS reader: ESP32
 - M-bus adapter (if applicable):

**Relevant firmware information:**
 - Version: 2.0.3
 - MQTT:  Yes
  - HAN GPIO: 16
 - Temperature sensors:  No  Is BME2x0 supported ?

**Comment by gskjold** [comment]
Thank you for the feedback, good to hear that it is appreciated :)  

Can confirm that the exchange rate for DKK doesn't work, I will look into it.

**Comment by gskjold** [comment]
Will be fixed in 2.0.5
