### ISSUE TITLE
Q about phase current report

### ISSUE THREAD

**Issue by angainor** [gskjold/AmsToMqttBridge#202]
I have updated my Pow-U to version 2.0.3. Right now, in the web interface I see Phase current bars for L1 and L3. Previously, in version 2.0.2 I also saw a bar for L2. Is there a reason why it's gone?

Another new user question: I often see those bars getting red and above 100%. I remember that L2 was much less used, and was never getting that high. I suspect that parts of the kitchen are on that line (oven, cooking top), but I am not sure. The question is (if that even is a right place to ask), do you think this is something with my electric installation that I should be worried about?

**Comment by ArnieO** [comment]
> The question is (if that even is a right place to ask), do you think this is something with my electric installation that I should be worried about?

Not if the installation is in general done according to rules and regulations. 

The disadvantage of not having your load (relatively) evenly distributed between phases is that the main safety breaker could trip in situations where it would not trip if load was better distributed. 

Did you set the fuse size correctly (configuration/meter)? That setting (only) scales the current bars.

**Comment by angainor** [comment]
@ArnieO Of course, my settings were wrong. My main fuse is 63A, I've updated it now. Thanks!
