### ISSUE TITLE
Nothing happen when using in place upgrade

### ISSUE THREAD

**Issue by ujhede** [gskjold/AmsToMqttBridge#203]
Nothing happen when uploading new firmware.

I have tried both uploading from the Firmware menu and choosing the "upgrade" link on the front page.  I am just left on the same version 2.0.3.

**Hardware information:**
 - Meter: Kamstrup Danish
 - AMS reader: ESP32 D1 clone
 - M-bus adapter (if applicable):

**Relevant firmware information:**
 - Version: 2.0.3
 - MQTT: yes
 - HAN GPIO: 16
 - Temperature sensors none.

**Comment by gskjold** [comment]
Yes, 2.0.3 has known OTA upgrade issues with ESP32. Seems like v2.0.4 is also suffering from same issue

**Comment by gskjold** [comment]
Final issue with OTA update on ESP32 will be fixed in v2.0.5. This version needs to be flashed by cable.
