### ISSUE TITLE
Unable to upgrade firmware through WEB.

### ISSUE THREAD

**Issue by hanseinar** [gskjold/AmsToMqttBridge#207]
**Describe the bug**
A few dayes ago. new ESP32 and flash 2.0.3 with esptool.py. 3 files, no error.

W10. Tryed to upgrade to 2.0.4 trough WEB, no luck. 
Same for 2.0.5.

IOS(Ipad mini)
Same, no luck.

Tryed both with and without web-security. Thought maybe that had something to do with it, but no luck.

**A clear description of what the bug is.**
What happend is:
Brows to new downloaded firmware file, hit upload.
Circle spinning for 18sek. then ERR_CONNECTION_RESET
Reload IP after a moment and the reader is back i buisness, but with old fw.
I'v also tryed the java-direct-link-upgrade. No luck.

**Hardware information:**
 - Meter: Aidon
 - AMS reader: ESP32 (TTGO)
 - Norway
 
**Relevant firmware information:**
 - Version: 2.0.3
 - MQTT: yes
 - HAN GPIO: GPIO13
 - HAN baud and parity: 2400 8E1
 - ENTSO-E API
 
**Additional context**
I had ESP8266 before, and firmware update trough web always worked perfect. Think I can upgrade with esptool.py but the esp is mounted a plase where it is hard to get, so perfect if web ugrade had worked. Perhaps I have to set something to enable flashing for my ESP32? 
BTW absolutely fantastic software!

**Comment by gskjold** [comment]
Unfortunately 2.0.3 and 2.0.4 has a code error preventing ESP32 from upgrading OTA. Cable upgrade to 2.0.5 is required.
