### ISSUE TITLE
Undecoded messages to MQTT

### ISSUE THREAD

**Issue by toreamun** [gskjold/AmsToMqttBridge#210]
It would be great if binary messages received from the HAN-port data stream could be published to a MQTT-topic. This would make a great fit with other solutions capable of parsing meter data from MQTT, like this Home Assistant integration: https://github.com/toreamun/amshan-homeassistant

Alternatives:
- Alt A: The format of the published message exactly as received from the meter (with or without flag-sequence at the start/end). Messages with invalid checksum and length can also be published (the receiver can validate the checksum).
- Alt B: Strip away the HDLC-framing and only publish the contained COSEM data in the APDU part. The data must be unescaped, and the checksum and expected frame length should be correct for the message to be published.

![image](https://user-images.githubusercontent.com/12134766/150108494-02164fd1-2c8e-4006-902c-00c2f13c6328.png)

**Comment by ArnieO** [comment]
Not sure if I understand the request, as MQTT is implemented, and data published to the topic you specify:
I'm currently not using MQTT, so this is just to illustrate:
![image](https://user-images.githubusercontent.com/10295178/150171491-489f28b6-08f8-46b7-bbc5-382ace046615.png)

**Comment by toreamun** [comment]
Maybe I read the documentation wrong. Payload format described in https://github.com/gskjold/AmsToMqttBridge/wiki/Message-formats are JSON, not the message in same format as received from the meter. The [MQTT documentation](https://github.com/gskjold/AmsToMqttBridge/wiki/MQTT-configuration) lists 4 formats (JSON, Raw full, Raw minimal and Domoticz). None of them are described as the original message from the meter. I have also looked at the [MQTT source code](https://github.com/gskjold/AmsToMqttBridge/tree/master/src/mqtt) and I cant see that any of them is what i suggest.

**Comment by ArnieO** [comment]
I read your initial message too rapidly, sorry!
What you request is a new option for MQTT formats, sending the raw data byte stream from the meter to MQTT (with or without HDLC framing).

So I will leave it to @gskjold to consider!

**Comment by toreamun** [comment]
Yes, raw data byte stream. Both options (with or without HDLC framing) is not needed, but at least one of them would be great. Tibber Pulse sends full HDLC frame and works fine with [AMSHAN custom integrationHome Assistant](https://github.com/toreamun/amshan-homeassistant) for Home Assistant. I am the maintainer of that integration.

**Comment by gskjold** [comment]
Agree this could be useful. Will implement support to send full frame as bytes to MQTT.
