### ISSUE TITLE
Solar panels, strange readings.

### ISSUE THREAD

**Issue by Isaksson** [gskjold/AmsToMqttBridge#211]
**Describe your problem**
Strange values after solar panel installation

**Hardware information:**
 - Meter: Aidon Sweden
 - AMS reader: ESP8266

**Relevant firmware information:**
 - Version: 2.0.4
 - MQTT: yes
 - HAN GPIO: UART2

Yesterday I got my solar panels installed and connected to the grid, and now the meter report very strange readings on my Phase current.
Have anyone seen this behavior before?
![image](https://user-images.githubusercontent.com/4119080/150322113-a21ec9f1-f812-44cd-9ef1-0710bae7f9a9.png)

**Comment by gskjold** [comment]
Thanks, I see now that current values pass through a unsigned int, will fix in next patch.

**Comment by Isaksson** [comment]
Yes, I just verified on my meter and its because the current has a negative value now when exporting to the grid.
Thanks.

**Comment by gskjold** [comment]
Try this version

[esp8266.zip](https://github.com/gskjold/AmsToMqttBridge/files/7915361/esp8266.zip)

**Comment by Isaksson** [comment]
Thanks for that, just installed the update, I used my mobile phone really nice to be able to update from mobile device 👍
Let's hope for some sun tomorrow so that I could verify this new version.

**Comment by Isaksson** [comment]
It's working as expected, thanks.
![Screenshot_20220122-095521_Chrome](https://user-images.githubusercontent.com/4119080/150631908-c229b4e9-e1b9-4bf1-a225-026ca971b088.jpg)

**Comment by gskjold** [comment]
Awesome! Thanks for confirming
