### ISSUE TITLE
Wrong lables in graphs

### ISSUE THREAD

**Issue by Lommelund** [gskjold/AmsToMqttBridge#213]
The graphs started to show wrong labels after  upgrade.  Meter is configured as TN 400V.

Have tried to switch between IT/TT and TN without any change. 

![Screenshot_20220120-220409_Chrome](https://user-images.githubusercontent.com/10024420/150423732-62447cec-e7ee-444c-9126-2318de3bc621.jpg)

**Hardware information:**
 - Meter:  Aidon
 - AMS reader:  Pow-U

**Relevant firmware information:**
 - Version: 2.0.5
 - MQTT: yes
 - HAN GPIO: [e.g. GPIO5]
 - HAN baud and parity: [e.g. 2400 8E1]

The device reboots more often after upgrade from 2.0.3 to .4 and .5. Before I could see uptime several days. Now i see max a few hours. 
I power it from USB.

**Comment by tronde-ams** [comment]
I guess this has something to do with a change made for 230V IT/TT meters.

For IT/TT this is correct, but for 400V TN it should read "Phase Voltage" and L1, L2, L3 as it was from the beginning. You do not show the labels for current, so I do not know if they changed as well. For 400V TN they should read "Phase current" and L1, L2 , L3 as from the beginning.

**Comment by Lommelund** [comment]
Both voltage and current show the same.
L1-L2, L1-L3, L2-L3.

**Comment by gskjold** [comment]
Fixed in next patch
