### ISSUE TITLE
PowU does not pulish accumulated power

### ISSUE THREAD

**Issue by paaland** [gskjold/AmsToMqttBridge#214]
**Describe the bug**
I've got a PowU connected to an Aiden meter in Norway. I can see in the UI that the accumulated power value reported by the meter change, but it's not reflected in the what's published in mqtt.

**To Reproduce**
1. Go to AMS reader web page
2. Open MQTT explorer, examine the meter/import/active/accumulated
3. The value should correspond with that's in the web page
4. It does not

**Expected behavior**
When a new accumulated value is received, it should be published to mqtt as all the other values.

**Screenshots**
<img width="249" alt="image" src="https://user-images.githubusercontent.com/172243/150956673-d063a6b3-5f49-4f01-801e-7294f300c67f.png">

**Hardware information:**
 - Aidon
 - Pow-U

**Relevant firmware information:**
 - Version: 2.0.6
 - MQTT: yes
 - HAN GPIO12
 - HAN baud and parity: 2400 8E1
 - Temperature sensors: none

**Additional context**
All the other values are published fine, it's just meter/import/active/accumulated that is not updated.

**Comment by gskjold** [comment]
You will only receive a confirmed accumulated value at the top of the hour (approx ??:00:10). What you are seeing in the GUI is a real time calculated value. This value is mostly correct, but can deviate a bit, both higher and lower, so there is a good chance you will see a small jump in the value when the confirmed reading is received.

**Comment by ArnieO** [comment]
So the value difference GUI vs MQTT is:
- GUI: Last hourly value from meter + estimated accumulated so far this hour 
- MQTT: Last hourly value from meter

**Comment by gskjold** [comment]
Thanks for the summary, yes, that is correct.

**Comment by paaland** [comment]
I "lost" a value too. I got a value at 11, then nothing at 12, but I got a value at 13. 
This cause the "previous" usage value to be reused. I think the whole thing might tie into this bug: https://github.com/gskjold/AmsToMqttBridge/issues/199

<img width="795" alt="image" src="https://user-images.githubusercontent.com/172243/150988282-395d5e5a-476f-4650-adbd-0b9f097cb03c.png">

**Comment by gskjold** [comment]
The graph is calculated from usage between successfully received meter readings (only received once every hour), if a reading is missed, the next calculation will be spread across all hours since last successful calculation. In your case, 9.8kwh have been used between 10-12 and was divided over the two hours.

**Comment by tronde-ams** [comment]
Is this real time accumulated power a special for ESP8266 based units? I have only seen real time values when I power up an ESP32 until it reaches hh:00:10. From then it is only updated once an hour.


![0159](https://user-images.githubusercontent.com/97398751/151085814-6b124859-f743-4bb3-abd0-4bea7edee91b.jpg)
![0200](https://user-images.githubusercontent.com/97398751/151085833-80035158-5744-4371-a9f8-d07c2527beb6.jpg)

No change after 15 min. I reloaded the page before each capture.
![0215](https://user-images.githubusercontent.com/97398751/151086775-9c02cb1e-1ccc-4f9e-9337-923031d9f6d4.png)

**Comment by Isaksson** [comment]
Could you please use the DevTools in chrome (F12) and verify on the Network tab that your browser is getting the updated data.
![image](https://user-images.githubusercontent.com/4119080/151617571-96b352e5-cb61-4616-8760-953ee8f97b74.png)

**Comment by tronde-ams** [comment]
I don't have chrome on my desktop, and I have no inttention to install it either.

I have not seen real time update on any of my ESP32 based units  regardless of using Vivaldi or Firefox on two different desktops, or Vivaldi, Firefox or Chrome on android. I have no ESP8266 to test with at the moment. 

It does show real time when powered up until first hh:00:10, but not after. 
My meter is Aidon three phase IT.



I cut power on one unit for a re-start.

Counts steadily from 0

![2102](https://user-images.githubusercontent.com/97398751/151622272-eb38ab78-cfe5-482a-82c7-2088bf289ee7.jpg)

![2127](https://user-images.githubusercontent.com/97398751/151622281-e2602157-61f7-476b-9153-392cb3d08f9a.jpg)

![2135](https://user-images.githubusercontent.com/97398751/151622293-f82ab897-f32a-41f9-8f3c-5271b315f14b.jpg)
![2144](https://user-images.githubusercontent.com/97398751/151622318-875bfd25-ac25-485c-94ca-ca3f7c1495d3.jpg)
![2148](https://user-images.githubusercontent.com/97398751/151622330-88830d78-a881-4530-b98e-69255823624d.jpg)
![2152](https://user-images.githubusercontent.com/97398751/151622340-0a8ecd8f-53a6-416b-b9ea-ab27f2196cfe.jpg)
![2159](https://user-images.githubusercontent.com/97398751/151622350-67d63bee-4587-42ef-aa88-4bed7675c0a0.jpg)

.


Fetches total from meter at 22:00:10
![2200](https://user-images.githubusercontent.com/97398751/151622443-41307f67-244e-4e04-ba7f-fbcd1ee46efc.jpg)


.
Then stops counting
![2217](https://user-images.githubusercontent.com/97398751/151622797-7d1702ad-46a7-4485-90d6-33440b8199a3.jpg)

**Comment by Isaksson** [comment]
There is a developer function in Firefox, if you are on Windows you open it with F12.
https://developer.mozilla.org/en-US/docs/Tools

That browser also have the network monitor function.

**Comment by tronde-ams** [comment]
Don't tell me much, I am afraid ;-(
![2022-01-28_224039](https://user-images.githubusercontent.com/97398751/151625469-a95944b7-407e-44f7-a5c2-37a4269e6640.jpg)

**Comment by Isaksson** [comment]
And you have to refresh the webpage to see any updates?
So between all the screenshots above you had to refresh the webpage?

**Comment by tronde-ams** [comment]
No, I don't need to. 

I did for the first screenshots three days ago to make sure nothing was stuck, but I did not refresh today.

First screenshot here is same as 22:00
![2259](https://user-images.githubusercontent.com/97398751/151627591-745aeefb-c5ad-4e71-9264-37ef9bc5515c.jpg)

Next without refresh is updated with value from meter at 23:00:10
![2300](https://user-images.githubusercontent.com/97398751/151627612-de341e73-2d6d-4dc5-9ad0-b608da2ea541.jpg)

**Comment by tronde-ams** [comment]
Previous screen shots was from Firefox

This is from Vivaldi. Same accumulated value, but seven minutes later, and different browser.
![2207](https://user-images.githubusercontent.com/97398751/151628334-12ebde65-0074-42d3-8a5b-79c6e965b0eb.jpg)

**Comment by tronde-ams** [comment]
Firefox on android. Still same value
![Screenshot_20220128-231144](https://user-images.githubusercontent.com/97398751/151628964-59e1fa34-edfc-450f-bd3f-ec86ae43daf8.png)
