### ISSUE TITLE
no data shown. Meter outputs something every 10 sec.

### ISSUE THREAD

**Issue by zaico** [gskjold/AmsToMqttBridge#215]
Hi

I can't seem to get data showing or verifying that the ESP8266 is reading the data.

I have an ESP8266 NodeMCU and have connected wires to GND and GPIO3 and to pin 5 and 6 on the meter.

I have received keys and input them in the AMS Web settings.

I have measured on pin 5 and 6 on the meter and it's giving 3.28v and every 10s dipping to 1.5v and then going back up to 3.28v so from what I can gather that means the meter is sending out data.

AMS reader is just not showing any data and HAN is read.

If I restart the esp HAN is green for 10 sec then turns yellow for 2-4 sec and then turns red.

debug shows nothing else then it took 0ms to update temp. 

I hope some of you with more knowledge than me can help me.

Best regards
Alex

**Comment by ArnieO** [comment]
Which country are you in? Pins 5 and 6 indicates to me you might be measuring on a meter with an RJ12 connector?

**Comment by zaico** [comment]
Never mind, it's working now. Out of sudden data has started to come in.

**Comment by ArnieO** [comment]
Dupont pins are not very reliable, you are not the first with this kind of issue.
Denmark and Kamstrup, I assume.

**Comment by zaico** [comment]
Yes Denmark and Kamstrup ;)

**Comment by zaico** [comment]
The setting for main fuse, do you know what impact that has on the data?

**Comment by gskjold** [comment]
https://github.com/gskjold/AmsToMqttBridge/wiki/Meter-configuration
