### ISSUE TITLE
Lolin D32 does not work with 2.0.9

### ISSUE THREAD

**Issue by gvenaas** [gskjold/AmsToMqttBridge#230]
**Describe the bug**
The version is installed, but the device is unstable
- Frequent restart
- HAN port green, but no readout
- Meter is not recognized

Tried to set debug to Error or Warning, but when connected to telnet it seems to force a reboot at once

**To Reproduce**
Update to 2.0.9

**Expected behavior**
A working device

**Screenshots**
--

**Hardware information:**
 - Meter: Kamstrup
 - Lolin D32
 - TTL converter

**Relevant firmware information:**
 - Version: 220124.2
 - MQTT: no
 - HAN GPIO: 16
 - HAN baud and parity: 2400 8N1
 - Temperature sensors No

**Additional context**
--

**Comment by gskjold** [comment]
Removed 2.0.9
