### ISSUE TITLE
Export W does not update in GUI

### ISSUE THREAD

**Issue by Isaksson** [gskjold/AmsToMqttBridge#232]
**Describe the bug**
Export W does not automatically updates when new data.json is fetched, its only the visible value that does not update, the graph does.
Refresh (F5) updates the value.

Its only the Export value, all other values is updated every time data.json is fetched.

**To Reproduce**

**Expected behavior**
Value updated
**Screenshots**
![image](https://user-images.githubusercontent.com/4119080/153193382-97c30dbb-9371-414e-8824-f3bb6b12b075.png)
![image](https://user-images.githubusercontent.com/4119080/153193437-27f76d40-4df4-4cf2-8f47-57d5015c5b92.png)

**Hardware information:**
 - Meter: Swedish Aidon
 - AMS reader: ESP8266
 - M-bus adapter (if applicable):

**Relevant firmware information:**
 - Version: 2.0.7
 - MQTT: Yes
 - HAN GPIO: UART2
 - HAN baud and parity: 2400 8E1
 - Temperature sensors: no

**Additional context**

**Comment by gskjold** [comment]
Thanks, actually fixed in next patch
