### ISSUE TITLE
Option to keep select watt as unit instead of KW

### ISSUE THREAD

**Issue by Nesegreven** [gskjold/AmsToMqttBridge#237]
**Is your feature request related to a problem? Please describe.**
If possible i think it would be nice to have the option to keep the granularity of watt as a unit.

**Describe the solution you'd like**
Keep watt as unit through option in settings and not switch to KW when usage is above 1000w

possible other
text size may need to be adjusted to not overflow onto the visual load indicator 

**Additional context**
I would use it to find unnecessary standby device and other watt-thieves, without having to turn off heating.

**Comment by gskjold** [comment]
I will consider how to best present this option in a future release.

**Comment by dknia** [comment]
I strongly support/endorse this request for exactly the same reason. 

I have recently purchased and installed the AMS, and this was more or less the first configuration item I was looking for.
