### ISSUE TITLE
Wrong label in MQTT config for domoticz

### ISSUE THREAD

**Issue by gsolem** [gskjold/AmsToMqttBridge#241]
Label for Voltage L2 and L3 IDX is wrong (all showing L1) for the Domoticz MQTT config. 

![image](https://user-images.githubusercontent.com/15731163/155193432-b30a5049-0387-470d-9674-4b5ffb26102e.png)

**Hardware information:**
 - Meter: Kamstrup
 - AMS reader: Pow-K

**Relevant firmware information:**
 - Version: 2.0.11

**Comment by gskjold** [comment]
Thank you!
