### ISSUE TITLE
Negative Phase

### ISSUE THREAD

**Issue by Isaksson** [gskjold/AmsToMqttBridge#245]
Today when the sun was shining and the house did not use that much energy, I noticed that when Phase Current was negative on all three phases the graph did not render.

At first the graph showed a positive value(when the Import was 0 W) at one of the phases (the same value last used before it went negative) then i reloaded the page and error message displayed "data table is not defined".

The screenshot is when I have reloaded the page when import is 0W
![Screenshot_20220305-110704_Chrome](https://user-images.githubusercontent.com/4119080/156879176-a0454a52-8d3c-4193-8c48-daea8545a247.jpg)

**Comment by Isaksson** [comment]
I think this is the issue, in application.js
![image](https://user-images.githubusercontent.com/4119080/156896556-6c0f2df1-1b2e-47a9-b382-40545f109aa4.png)

When all phases have a negative value then a = 0 and then it will not draw the chart.
![image](https://user-images.githubusercontent.com/4119080/156896607-61e759a8-9c78-417b-8d73-d98a16929813.png)

**Comment by gskjold** [comment]
Thanks!
