### ISSUE TITLE
Describe json for prices

### ISSUE THREAD

**Issue by thomaspalmdk** [gskjold/AmsToMqttBridge#258]
Please describe the json result from the Entso-E prices in the documentation.

Example of data:
{
   "id":"yy:yy:yy:yy:yy:yy",
   "prices":{
      "0":0.2000,
      "1":0.2295,
      "2":0.1991,
      "3":0.1644,
      "4":0.1506,
      "5":0.1201,
      "6":0.2007,
      "7":0.2043,
      "8":0.1950,
      "9":0.1819,
      "10":0.1863,
      "11":0.2007,
      "min":0.1201,
      "max":0.3236,
      "cheapest1hr":"2022-03-30T21:00:00Z",
      "cheapest3hr":"2022-03-30T19:00:00Z",
      "cheapest6hr":"2022-03-30T19:00:00Z"
   }
}

Example of documentation, like in the wiki for "message formats":
{
    "id" : "",     # WiFi MAC address
   "prices":{.   # Prices fetched from Entso-E
      "0":0.2000,       # price of current time range +24h in future
      "1":0.2295,       # price of +1 hour from current time range +24h in future
      "2":0.1991,       # price of ...
      [...]
}

**Comment by gskjold** [comment]
https://github.com/gskjold/AmsToMqttBridge/wiki/Message-formats
