### ISSUE TITLE
2.1.0 does not update prices over MQTT

### ISSUE THREAD

**Issue by tronde-ams** [gskjold/AmsToMqttBridge#259]
ESP32 / 2.1.0 / aidon 3p IT / Norway.

One ESP32 with 2x DS18B20, one without sensors. GPIO 16

Prices are not updated as raw MQTT. I have tried both full and minimal. I have not tried MQTT as JSON.
WEB GUI and /energyprice.json are correct.

![2350](https://user-images.githubusercontent.com/97398751/160946788-59848060-e0f3-4241-a9f8-716230837521.jpg)

![0028](https://user-images.githubusercontent.com/97398751/160946798-fe1fc326-348e-4e69-930a-517dbe267919.jpg)
![0103](https://user-images.githubusercontent.com/97398751/160946805-108e4117-a201-4702-99a1-af8cbf1da64a.jpg)

**Comment by gskjold** [comment]
Do I interpret this correctly that this only occurred at midnight? Or does it happen more often?

**Comment by tronde-ams** [comment]
The prices shown above did not change after I updated to 2.1.0. It was not just at midnight. I updatet wery short time after the new code was published.


The prices did change when new prices was fetced today, but not after.
.

This is from 15:23 when the correct price is 2,41 (multiplier = 1.25 and NO1) as shown in the /energyprice.json but wrong in the MQTT data.
![2022-03-31_152355](https://user-images.githubusercontent.com/97398751/161066500-6cc277a5-fc3c-45b0-b6b2-45403b12455d.jpg)

**Comment by ujhede** [comment]
While at the subject of prices via MQTT.  Is it correct that prices are Prices Sensors are not created in Home Assistant mode ?

**Comment by tronde-ams** [comment]
Prices did not change until midnight. New prices are wrong.
![1 april](https://user-images.githubusercontent.com/97398751/161159506-1f5c2629-277e-4cf1-b48c-9941ad7f6904.jpg)

**Comment by gskjold** [comment]
@ujhede Correct, there are no price sensors defined in the code. Seems that this was not covered in the initial implementation

**Comment by gskjold** [comment]
@tronde-ams Found the problem, currently testing a fix

**Comment by tronde-ams** [comment]
Mostly OK by now, but some strange result for raw full format.

It can be that emqx and mosquitto handles things differently. 
I use two different brokers because that was most convenient for my android app but  I will change if you tell me what to test for


Emqx is OK
![ok](https://user-images.githubusercontent.com/97398751/161354802-071271e4-7e4d-48bd-9613-6cbecde9b401.jpg)

but mosquitto does not delete all old values. It has deleted 23 and 24, but not after that.

![fail](https://user-images.githubusercontent.com/97398751/161354874-40389c18-8957-490b-a264-1e21bd103bed.jpg)

**Comment by tronde-ams** [comment]
Both units have fetched new prices, and both are deleting old prices as they should do. The trouble can have been because both units was updated after 14:00 yesterday, and the mosquitto unit some hours after the emqx unit so some prices from earlier had been stuck.

Your new code appears to be OK.

**Comment by tronde-ams** [comment]
Still strange things going on...

Everything was OK until midnight. Both units updated prices and deleted old.


The mosquitto unit started to show old prices again (25 and older) while the EMQX unit was still OK.
![2022-04-03_000831](https://user-images.githubusercontent.com/97398751/161405947-9afcf47f-5907-4e7d-9bfb-5d368a41122a.png)
![2022-04-03_000800](https://user-images.githubusercontent.com/97398751/161405951-801a1a39-c2c3-4fb2-a713-16dec76fe2b3.png)

I understand next to nothing about how these procesesses are meant to work, so I can only tell what I see.

Since the error repeated from yesterday, I choose switch the MQTT format on both units to see if the problem is related to mosquitto.

As of now EMQX receives MQTT raw minimal and mosquitto raw full.

Nothing changed, but maybe a new ftching of prices and a new midnight will tell more. I will report back.



![2022-04-03_021449](https://user-images.githubusercontent.com/97398751/161406114-0ed01ec9-a3c7-461c-96ce-5edcd77c3ad0.png)

![2022-04-03_021411](https://user-images.githubusercontent.com/97398751/161406115-696f7aec-f155-4004-baee-3b71b819de5b.png)

**Comment by tronde-ams** [comment]
Two similar units with same conguration for prices, and different prices shown ???
I must have happened when or after I switched the MQTT.

This unit is EMQX
![2022-04-03_041236](https://user-images.githubusercontent.com/97398751/161408288-f30502ef-c507-4b21-ac23-25b784238d6d.png)
![2022-04-03_041259](https://user-images.githubusercontent.com/97398751/161408293-561f449d-86fb-45dd-8c0e-7c5ea72ba187.png)
![2022-04-03_041318](https://user-images.githubusercontent.com/97398751/161408494-d631ce78-2e97-41b7-a7a2-177693b18b9f.png)


![2022-04-03_041754](https://user-images.githubusercontent.com/97398751/161408382-dec39ef0-b2a7-46e6-a96b-1f2732ebbd53.png)
*
*
*
This unit is Mosquitto 
![2022-04-03_041347](https://user-images.githubusercontent.com/97398751/161408297-d194bce6-355b-421d-8a0a-65abcdc254d9.png)
![2022-04-03_041405](https://user-images.githubusercontent.com/97398751/161408298-89694d5d-2da0-401c-98bf-06239688532f.png)


![2022-04-03_041432](https://user-images.githubusercontent.com/97398751/161408501-3e8c7135-0c5d-4da4-ad9c-8fdcd3deb568.png)

![2022-04-03_041721](https://user-images.githubusercontent.com/97398751/161408383-c0283c54-8ecf-4f23-8e18-5489d67b38bc.png)

**Comment by gskjold** [comment]
I have adjusted the code so that it will clear all unknown prices instead of just the first one.

As for the difference in price between your two units, I do not yet understand how that could happen. I will have to set up a test with two units to compare.

**Comment by tronde-ams** [comment]
I have updated one unit to 2.1.1. The unit which ended up showing corrupt prices seems to have gone haywire.  I can flash it with USB, and the flasher says hash is OK, but then nothing. It shows up as 192.168.4.1 when I scan the AMS2MQTT network, so it is some kind of life. 

The remaining unit is set to push raw full to mosquitto, since that was the initial problem.

I have one spare unit but I must prepare some hardware first.

Please tell me if you want me to test something specific.

**Comment by tronde-ams** [comment]
I wiped the flash on the corrupted unit, flashed it to 2.1.1, and it is now back on air. I have two units for testing, so tell me what to do with them.

I modified the saved config file from the other unit (changed IP and hostname) and uploaded it to the newly flashed unit. It did not use the saved API-key. I think I have seen this before too, but not worried about it. It can be you shuld check if it is a bug.

**Comment by tronde-ams** [comment]
At 01:50 it seems like it is OK.

Both units (one raw full and one raw minimal) behave the same way.


The only thing I notice, is that before midnight deleted prices does not show up in the list,,
![2022-04-04_014810](https://user-images.githubusercontent.com/97398751/161454511-593fe01c-317d-4316-8be3-1b3c459a5fa4.png)

.
while they show up as 0 after midnight, with the exception of the deleted value from the most recent hour being omitted. 

I don't think this is a problem. I just tell what I see.
.

![2022-04-04_014724](https://user-images.githubusercontent.com/97398751/161454603-72f643f5-462b-4f9b-b6cd-099fcb5c7cc0.png)
![2022-04-04_014741](https://user-images.githubusercontent.com/97398751/161454606-ceae31d2-1962-4c00-9e53-782dc0cec785.png)

**Comment by gskjold** [comment]
Good catch, I think I see why that happened, firmware attached.

As for the API key not being loaded from config file, I cannot see a reason from the code, but I will test that later.

[esp32.zip](https://github.com/gskjold/AmsToMqttBridge/files/8406936/esp32.zip)

**Comment by tronde-ams** [comment]
Is this the correct file?
It shows as 2.1.0 and the files are from 2022-03-30

**Comment by gskjold** [comment]
Hah, I tricked myself, here you go.

[esp32.zip](https://github.com/gskjold/AmsToMqttBridge/files/8410118/esp32.zip)

**Comment by tronde-ams** [comment]
a0d3632

Raw full seems to be Ok.

Some strange result for raw minimal, but it can be this is not a problem, but a result of old prices not being cleared on the broker?
It was carried over when I updated. I will report back when new prices have been fetched.

![2022-04-04_160428](https://user-images.githubusercontent.com/97398751/161648112-53aacce3-5b4a-453d-aabb-90a6cbfc67e1.png)
![2022-04-05_011353](https://user-images.githubusercontent.com/97398751/161648117-698675ab-7e01-4045-ba4d-17de0c1f3121.png)

**Comment by gskjold** [comment]
Weird, it should have cleared them.. Maybe I'm doing it wrong, will investigate.

**Comment by tronde-ams** [comment]
Still nutters for raw minimal. I have set the mosquitto unit to push raw minimal as well now, to see if it behaves the same way.


![2022-04-05_181213](https://user-images.githubusercontent.com/97398751/161802655-474a6277-c1ea-4118-9378-6ffec3e2f2e8.png)
![2022-04-05_182014](https://user-images.githubusercontent.com/97398751/161802673-d794e21d-ecba-43ed-a51b-85996ce6ab14.png)

**Comment by tronde-ams** [comment]
I have been testing more. MQTT raw minimal sent to test.mosquitto.org seems to be OK, just as raw full.

The module which has been connected to EMQX shows some strange behaviour. It can be defective in a way, but the strangeness is only related to prices.  I will try to find a replacement tomorrow. 

It would be nice if someone else could try MQTT raw minimal to broker.emqx.io. It can be I am chasing ghosts...

**Comment by gskjold** [comment]
Interesting stuff, and thank you for thoroughly testing this. I can't see that the topic for prices should behave any different in minimal vs full, it always publish the same data. But there is a chance this could be related to MQTT buffer size maybe, not sure, gussing. 

Any difference in length of topic? Special characters? Assuming it uses SSL? I've never tried these cloud based brokers. Just need some info to set up a proper test environment when the time comes.

Hopefully in Easter I will have some time to look more into this.
