### ISSUE TITLE
Timetamp in JSON Dayplot

### ISSUE THREAD

**Issue by O2Ben** [gskjold/AmsToMqttBridge#266]
The JSON dayplot, http://<ams_hostname>/data.json  should have a timestamp, date and starting hour for the first element in the list ("i00"). This to assure that you are logging consumption correctly.

**Comment by gskjold** [comment]
data.json has the field "c" which contains the clock in epoch. Local time and date can be calculated from this. "i00" is UTC 00:00 and can be adjusted for local timezone by code.
