### ISSUE TITLE
SAGEMCOM T211

### ISSUE THREAD

**Issue by christianritella** [gskjold/AmsToMqttBridge#267]
From a closed issue, #253 

I have connected RX to D7 and HAN=UART2/GPIO13.
Baudrate 115200 Parity 8N1
I have tried invert on/off;
Invert off: (W) (readHanPort) Unknown data format 40
invert on: (W) (readHanPort) Unknown data format 3F
Does this indicate that it is receiving data?
Is it possible to monitor received data from debug?

I have no resistors connected.

Any other suggestions?

**Comment by ArnieO** [comment]
Any other suggestions?

Please try a Telnet debug:
System/Debugging: Select Telnet and Verbose mode
Open a command window on your PC, and write "telnet 'IP-address of device' "
You may need to activate telnet, as it is by default disabled on Windows (how to do that: Google).
Then paste here what you get.

**Comment by gskjold** [comment]
You are definitely receiving data, and like @ArnieO suggested, it would be useful if you run verbose logging so that we can see a full datagram to try determine if we are receiving an unknown payload or if there is some kind of data corruption.

**Comment by christianritella** [comment]
Here is the output from Verbose;

(D) (readHanPort) Frame dump (1b):
(D) 3F
(W) (readHanPort) Unknown data format 3F
(D) (loop) Used 0 ms to update temperature
(D) (readHanPort) Frame dump (1b):
(D) 3F
(W) (readHanPort) Unknown data format 3F
(D) (loop) Used 0 ms to update temperature
(D) (readHanPort) Frame dump (1b):
(D) 3F
(W) (readHanPort) Unknown data format 3F
(D) (loop) Used 0 ms to update temperature

**Comment by ArnieO** [comment]
So did you try to invert the signal?
![image](https://user-images.githubusercontent.com/10295178/165054215-58aa6896-fcd9-4d9c-8db8-f6fae05821d1.png)

**Comment by ArnieO** [comment]
Could you send screenshot of your Config/meter and System/GPIO screens?

**Comment by christianritella** [comment]
Debug with was with invert, same result with it off.
![image](https://user-images.githubusercontent.com/86061619/165120916-4698992f-3f7f-4b4b-a78c-32e5259a1f14.png)
![image](https://user-images.githubusercontent.com/86061619/165121061-6e7b758a-86e6-4f95-8f84-95cebe5177ea.png)
![image](https://user-images.githubusercontent.com/86061619/165121410-7ab4e980-802c-4797-8341-7239c5adca40.png)

**Comment by ArnieO** [comment]
Thank you; I see no issues here. 

I'm re-reading your previous messages now and see that I don't quite understand this: "I have connected RX to D7 and HAN=UART2/GPIO13." So maybe there is some misunderstanding here?

You should connect the DATA pin from the P1 connector to UART2/GPIO13, which should be D7 pin on your board. In order to receive data from a P1 port you also need to pull D_Rqust high, please see below snippet of a circuit diagram for a device connecting to P1 port.

**Important note:** The DATA output on the P1 port is Open Collector, meaning you need a pullup resistor on in to 3,3V as indicated (R5 in the below diagram).

![image](https://user-images.githubusercontent.com/10295178/165136826-9d3b3cce-c6e2-4210-b010-cc5dce1fc72f.png)

**Comment by christianritella** [comment]
I think I understand, give me a couple of days...

**Comment by ArnieO** [comment]
Great! 👍 
The red ESP is an indication your voltage is low, or to be exact: that the voltage as read by the firmware is low. 
![image](https://user-images.githubusercontent.com/10295178/165582182-f779e051-3c61-422f-b861-843338de371c.png)

In System / GPIO you need to enter the resistor values of the voltage divider on your NodeMCU into "GND resistor" and "Vcc resistor", and select the correct GPIO input in "Vcc".
These fields:
![image](https://user-images.githubusercontent.com/10295178/165583412-fa9bbf07-4ce1-4dc7-928a-93453e1ee2e8.png)

This page indicates that the values are 100k and 220k but please check if that is correct for your board. 
https://circuitsgeek.com/guides-and-how-to/esp8266-adc-tutorial-read-nodemcu-analog-input/

**Comment by ArnieO** [comment]
With correct values you will then get close to correct value. You can calibrate it by adjusting "Multiplier" on the same page. 

Measure Vcc on your board, and adjust multiplier until you read correct voltage.

**Comment by gskjold** [comment]
> This page indicates that the values are 100k and 220k but please check if that is correct for your board

Although this is correct, the voltage divider on NodeMCU is intended for ADC input, which is disabled in this firmware since ADC_VCC is enabled. When ADC_VCC is set, nothing should be connected to ADC pin, but as you have pointed out there is on NodeMCU. This interferes with internal Vcc sensor, so the only way to get a semi-accurate reading is to adjust Vcc multiplier until you get a sane value. Guessing 1.11 (which is what I use for D1 mini)

**Comment by ArnieO** [comment]
> Although this is correct, the voltage divider on NodeMCU is intended for ADC input, which is disabled in this firmware since ADC_VCC is enabled. When ADC_VCC is set, nothing should be connected to ADC pin, but as you have pointed out there is on NodeMCU. This interferes with internal Vcc sensor, so the only way to get a semi-accurate reading is to adjust Vcc multiplier until you get a sane value. Guessing 1.11 (which is what I use for D1 mini)

OK, thank you for clearing up my misconception! 
I believe the reason this inconvenience cannot be managed in code is that ADC read from GPIO pin vs ADC reading from internal Vcc is a selection that must be done at compilation/build level - right?

**Comment by gskjold** [comment]
That is correct, we would need to have a "ADC" version of the ESP8266 firmware to resolve that issue. Not too sure it is that important. The multiplier adjustment is a usable fix I think.

**Comment by ArnieO** [comment]
> That is correct, we would need to have a "ADC" version of the ESP8266 firmware to resolve that issue. Not too sure it is that important. The multiplier adjustment is a usable fix I think.

Definitively not worth a separate version, your workaround is the way to go.
