### ISSUE TITLE
Turn off LED

### ISSUE THREAD

**Issue by duftstenen** [gskjold/AmsToMqttBridge#269]
Hi. Is there anyway to turn off the LED, so it is not blinking with the different status? I have tried to pick different pins etc but nothing seems to disabling it.

**Comment by ArnieO** [comment]
I assume this is related to the Pow-K (or possibly Pow-U) that I sell from https://amsleser.no/. 

You are not the first to ask, as I understand there are situations where the meter is in a location where the light can be a disturbance at nighttime. 

The blue blinking is intentionally directly connected to incoming data; the purpose being to be sure (independent of the status of the microcontroller) that there is incoming data from the meter. There is currently no way to turn it off from the user interface. However, I will consider adding such an option in a future design update, at least for Pow-K as there is plenty of space available for the few added components that would be needed.

My best advice is to either dim it down with a black felt tip pen directly on the LED, or cover the opening with a black tape.

On the latest version [Pow-K+](https://amsleser.no/hjem/1-pow-k-kamstrup.html) the LED is smaller and the resistor values are larger - so the light is less powerful.

**Comment by duftstenen** [comment]
Got it. Thanks
