### ISSUE TITLE
Show status and error messages in UI

### ISSUE THREAD

**Issue by gskjold** [gskjold/AmsToMqttBridge#27]
In web ui:
- Show RSSI (and other details?) from WiFi
- Show MQTT connected or not as well as last error
- Show VCC (and other details?) from ESP
- Show last error from HAN

**Comment by gskjold** [comment]
Showing WiFi RSSI, SSID and channel as well as MQTT errors and VCC.

**Comment by ArnieO** [comment]
WiFi RSSI should also be sent with the initial MQTT "Connected!" message.

**Comment by ArnieO** [comment]
Maybe me using PlatformIO the wrong way, but after building dev-v1.1.0 there is no change in the GUI:
![image](https://user-images.githubusercontent.com/10295178/74573157-842a6300-4f80-11ea-9d96-6dc538bf9f57.png)
