### ISSUE TITLE
Feature request:Read external temperature sensor, via network

### ISSUE THREAD

**Issue by borgemohus** [gskjold/AmsToMqttBridge#277]
Would it be possible to insert temperature data from an external sensor via the network?

I have some old 433MHz temp-sensor which I read with an rtl-sdr (software defined radio).
The temperature is the manipulated (replaced -127.00 with actual value) into the json from mosquitto.
It might be better if this could be done at the AmsToMqttBridge.

Several possibilities could be:
Use netact/ftp to send a formated string to a specific port of the AmsToMqttBridge ?
Make AmsToMqttBridge subscribe to a MQTT-server to get sensor data ?
Make AmsToMqttBridge use an API towards i.e Netatmo or yr.no to get nearby temp-data ?

If any of these solutions would be possible, the temperature then could be included in the mqtt out of the AmsToMqttBridge.

BR Børge Mohus

**Comment by gskjold** [comment]
The temperature sensor in ams-reader is meant for sensing the temperature inside your breaker box and not really the outside temperature (although some may use it for this as well). I'm sorry to say that I will not change or expand the functionality of the temperature sensor stack. Not many people use the temp sensor feature in the first place and the project is already exhausting the memory limitations of ESP8266.
