### ISSUE TITLE
Update to Supported Hardware in Wiki

### ISSUE THREAD

**Issue by PerJarlemark** [gskjold/AmsToMqttBridge#282]
I can confirm that this is working on "Kamstrup DK-8660 Omnipower Three-phase meter” currently located in Sweden

**Tested Meter.**
Model: Kamstrup DK-8660 Omnipower Three-phase meter
Parity: 8N1
Baud rate: 2400

**Country**
Sweden

**Grid operator**
Boo Energi [https://www.booenergi.se/](url)
Require Encryption Key = Yes

**AMS reader**
version 2.1.1

**Comment by ArnieO** [comment]
Hej @PerJarlemark - is your meter really encrypted?
I did not think encryption is used in Sweden?

**Comment by PerJarlemark** [comment]
Not sure if every meeter in Sweden is, but i need the encryption key for it to work, i think the grid operator mentioned something that they whee still running the nowegian standar on my meeter 
, and that this might change in the future

**Comment by ArnieO** [comment]
Thank you for confirming!

**Comment by ArnieO** [comment]
@PerJarlemark 
We checked with Boo Energi, and apparently they do not encrypt:
![image](https://github.com/UtilitechAS/amsreader-firmware/assets/10295178/496857d6-c82a-49bb-8acd-ab2593bd8b9b)

**Comment by ArnieO** [comment]
The encryption thing can a bit confusing. 
I have a suspicion that the firmware will interpret correctly non-encrypted meters even if you enter an encryption key. 
maybe try to remove it - and see what happens?

PS
I recommend upgrading your firmware to the latest version!

**Comment by gskjold** [comment]
It will only use encryption key if the payload specifies that the data is encrypted

**Comment by PerJarlemark** [comment]
Ok , have tried to remove it and you are right, it still runs fine so I guess Boo Energi is not using encryptions, (anymore?)

My setup is rock stable so will not update firmare right now (don´t fix if its not broken)

**Comment by ArnieO** [comment]
> don´t fix if its not broken

😆
