### ISSUE TITLE
Some details regarding the Sagemcom T210-D

### ISSUE THREAD

**Issue by cmock** [gskjold/AmsToMqttBridge#286]
I have two enhancement suggestions for the wiki, after getting the software to work with my Sagemcom T210-D by Netz Niederösterreich.

The first is that this meter is using encryption -- that column is empty in the wiki.

The second is that there is a very cheap and simple way to interface with this meter (and maybe other meters that are M-Bus masters): just lower the M-Bus voltage levels with a resistive divider (100k to M-Bus +, 5k6 to GND/M-Bus -, ESP UART pin goes in the middle). Tested with an ESP32, this relies on the fact that the logic levels on the ESP32, contrary to the datasheet, seem to be "lower than/higher than VCC/2".

This definitely is out of spec and not galvanically isolated, but it works reliably for me.

**Comment by ArnieO** [comment]
> This definitely is out of spec 
I'm not so sure that it is out of spec. 
And it's a bit more tricky if you generate your 3,3V from the M-bus, as the 3,3V could fluctuate a bit, so that Vcc/2 becomes a "moving target".

**Comment by gskjold** [comment]
Updated wiki for encryption. Have not added anything about the voltage divider.
