### ISSUE TITLE
Stability issues

### ISSUE THREAD

**Issue by rene-bayer** [gskjold/AmsToMqttBridge#288]
**Describe your problem**
The reader isn't up for more than half an hour.

The longest uptime I saw so far have been around 45 minutes.

Mostly the uptime is around a couple of minutes.

(Edit: already tried different boards, all the same)

**Hardware information:**
 - Meter: Sagemcom T210-D
 - AMS reader: ESP32 (Wemos Lolin32)
 - M-bus adapter (if applicable): TSS721 Modul

**Relevant firmware information:**
 - Version: 2.1.3
 - MQTT: yes
 - HAN GPIO: GPIO16
 - Temperature sensors: NaN

**Comment by gskjold** [comment]
Some quick questions I also have:
Which country?
Do you use meter encryption?

**Comment by rene-bayer** [comment]
Country: Austria
Grid Operator: Netz Niederösterreich GmbH
Encryption: Yes

It does work so far, even with regular rebooting esp the readings are always up to date in Home Assistant via MQTT.

I wouldn't have noticed the reboots if I wouldn't monitor the esp :-)

**Comment by cmock** [comment]
I have the same issue and the same meter and grid operator (and obviously, encryption), but with a simple voltage divider as the M-Bus interface (#286 ).

I have enabled telnet debugging at level "debug" and saw nothing relevant.

**Comment by gskjold** [comment]
Thanks for confirming. I think maybe I know what this is, I will make some adjustments for you to test with.

**Comment by cmock** [comment]
I have now added logging for the reset_reason to the setup() code, and what comes back is 12 -- "Software reset CPU".

**Comment by tmolberg** [comment]
Also having this issue, looks to be resetting on an random basis however. 

I had good luck using v1.4 for a long time but wanted to try out the home assistant integration. Is it possible to backport this feature?

**Comment by gskjold** [comment]
How often is the reboot?

Backporting would not be the easiest of jobs, but possible of course. I have enough with bug fixing and adding features, so not a job I would consider.

**Comment by gskjold** [comment]
Please test newly release 2.1.4

**Comment by cmock** [comment]
Looks very good for me: The reader hasn't rebooted since I upgraded yesterday afternoon, while before it could stay up for an hour at most.

**Comment by gskjold** [comment]
Excellent! Upgrade to 2.1.5 if you care about the real time data stored in flash :)

**Comment by rene-bayer** [comment]
Yes ... seems to work now without reboots.

Thank you for fixing :)

**Comment by rene-bayer** [comment]
Needed to revert to unstable firmware because of: https://github.com/gskjold/AmsToMqttBridge/issues/293
