### ISSUE TITLE
Real time calculation don't show negative Values

### ISSUE THREAD

**Issue by evhetlan** [gskjold/AmsToMqttBridge#291]
**Describe the bug**
Real time calculation don't show negative Values, only show 0 
See attach

![AMS2](https://user-images.githubusercontent.com/110242351/181780644-ebbd49f8-339e-46ba-ae27-0438eb258ba3.JPG)

**Comment by gskjold** [comment]
Funny, I was thinking about this while driving yesterday, what a coincidence that it is reported later the very same day. I think the correct solution here would be to add another line for export day/hour/month. Will look into this for future release.

**Comment by evhetlan** [comment]
Is It possible to get these values as export?
![image](https://user-images.githubusercontent.com/110242351/182025500-51a9b942-d4d8-4ef1-bc02-103ece3a9938.png)

**Comment by gskjold** [comment]
Please test attached firmware:
[esp32.zip](https://github.com/gskjold/AmsToMqttBridge/files/9298494/esp32.zip)
[esp32s2.zip](https://github.com/gskjold/AmsToMqttBridge/files/9298495/esp32s2.zip)
[esp8266.zip](https://github.com/gskjold/AmsToMqttBridge/files/9298496/esp8266.zip)

**Comment by evhetlan** [comment]
Hei
Supert, mye bedre nå 🙂
Takk!

[cid:0c6506be-46df-4527-af4c-af681bcc3429]
________________________________
Fra: Gunnar Skjold ***@***.***>
Sendt: onsdag 10. august 2022 10:56
Til: gskjold/AmsToMqttBridge ***@***.***>
Kopi: evhetlan ***@***.***>; Author ***@***.***>
Emne: Re: [gskjold/AmsToMqttBridge] Real time calculation don't show negative Values (Issue #291)


Please test attached firmware:
esp32.zip<https://github.com/gskjold/AmsToMqttBridge/files/9298494/esp32.zip>
esp32s2.zip<https://github.com/gskjold/AmsToMqttBridge/files/9298495/esp32s2.zip>
esp8266.zip<https://github.com/gskjold/AmsToMqttBridge/files/9298496/esp8266.zip>
