### ISSUE TITLE
You can't see numbers when the values are negative

### ISSUE THREAD

**Issue by evhetlan** [gskjold/AmsToMqttBridge#292]
You can't see numbers when the values are negative, please make the number A another color. See pic.

![image](https://user-images.githubusercontent.com/110242351/182349897-1707aa6d-fca0-4bdb-8bc2-85dfd3fcfd1b.png)

**Comment by ArnieO** [comment]
Strange... I had solar panel on my roof last summer, and can't remember having seen this. But there has been x firmware-updates since that; something may have been adjusted in the mean time - @gskjold ?

**Comment by gskjold** [comment]
I think maybe there have been a change since then, yes. Export has a separate bar. I have made changes to fix this issue in next release.
