### ISSUE TITLE
No Power Factor from Kamstrup Hoganas Energi 

### ISSUE THREAD

**Issue by Iridabike2** [gskjold/AmsToMqttBridge#295]
All 4 powerfactors PF, PF1, PF2 and PF3 always give zero values.   Appears to be a problem either in the  meter or in AMS_OBIS_POWER_FACTOR decoding in EC6205675.cpp.

**Comment by gskjold** [comment]
Are you sure you have a meter that should provide this information? The only Kamstrup setup I know that reports this is the encrypted ones in DK.

**Comment by Iridabike2** [comment]
I am not sure if the meter is sending it out so that could be the issue.  It's a Swedish Kamstrup 8660.  Everything else is working well and there is no encryption set.  I can make a work around and calc the PF from Reactive Power and the Real Power.

**Comment by gskjold** [comment]
Most likely PF is not included in the payload
