### ISSUE TITLE
Bug in v2.1.5: On ESP32-S2, pressing AP button does not bring up access point. 

### ISSUE THREAD

**Issue by ArnieO** [gskjold/AmsToMqttBridge#298]
**Describe the bug**
On programmed and pre-configured devices using ESP32-S2: Press/hold AP button does not present access point. LED blinks yellow as normal - but no access point is detectable.

**Hardware information:**
 - Country: Norway
 - Meter: Not applicable
 - Encryption enabled: Not applicable
 - AMS reader: Pow-K+

**Relevant firmware information:**
 - Version: 2.1.5
 - MQTT: Not applicable
 - HAN GPIO: UART2/GPIO16
 - HAN baud and parity: 2400 / 8N1
 - Temperature sensors: No
 - ENTSO-E API enabled: No

**Workaround**
Do an emergency reset by holding AP button during first second of reboot, while LED is green. Let button go when LED is steady red. The device will then start blinking yellow - and access point AMS2MQTTis visible as normal.

**Additional context**
**EDIT**: No issues with ESP8266.

**EDIT 2**
- Rollback to v2.1.4 tested: Same issue
- Rollback to v2.1.3 tested: No issue, access point comes up as expected.

So the bug seems to have been introduced with v2.1.4.

**Comment by gskjold** [comment]
Seems to be a result of me updating arduino-esp32 to 2.0.4, reverting to 2.0.3 for next patch.
