### ISSUE TITLE
Can not  enter meter type and model

### ISSUE THREAD

**Issue by Duckshousemacservice** [gskjold/AmsToMqttBridge#308]
**Describe your problem**
Can not enter meter type and model

the fields are grayed ut

**Hardware information:**
 - Country: danmerk
 - Meter: kamstrup
 - Encryption enabled yes
 - AMS reader: ESP32 

**Relevant firmware information:**
 - Version:  2.1.7
 - MQTT: yes
 - HAN GPIO: GPIO3
 - HAN baud and parity:  2400 8E1

 - ENTSO-E API enabled: no

**Comment by gskjold** [comment]
These are no longer user definable fields. On most meters this will be autodetected, but on some it remains blank. If you truly have 2400 8E1 like you have specified above, change to parity 8N1 which is correct for your meter. More in wiki: https://github.com/gskjold/AmsToMqttBridge/wiki/Known-hardware-configurations

**Comment by Duckshousemacservice** [comment]
i did have 8E1.  sorry.   but i still cant connect. i tried all 3 uarts.  with 8n1...  ill contact my provider.

**Comment by gskjold** [comment]
How have you connected the HAN port to your hardware?

**Comment by Duckshousemacservice** [comment]
a header on 2 wires.  1 to ground and 1 til gpio 16.  first pin i han is ground and second is tx data out. as i understand...

**Comment by gskjold** [comment]
Then UART2 is your friend. I am not sure of the Kamstrup pinout, but I had this image on disk that may or may not be correct:
![pinout](https://user-images.githubusercontent.com/4446828/187640828-ac949994-44a3-46f8-b085-ba9ed4ed2131.png)

**Comment by Duckshousemacservice** [comment]
it is correct according to the info i got from my provider Andel A/S. ill try uart2 and if its not working ill grab a new board. i might killed it during research....  thanks for the quick answering!

**Comment by ArnieO** [comment]
> I had this image on disk that may or may not be correct:
> ![pinout](https://user-images.githubusercontent.com/4446828/187640828-ac949994-44a3-46f8-b085-ba9ed4ed2131.png)

It is correct.
https://github.com/ArnieO/SmartMeterDocumentation#han-interface-description

**Comment by Duckshousemacservice** [comment]
got it now.  new esp did the trick. thanks a lot. now off to tinker more...
