### ISSUE TITLE
last hour usage

### ISSUE THREAD

**Issue by kitten77** [gskjold/AmsToMqttBridge#310]
Would it be possible to include the last hour of usage as a variable in the data.json set?

**Comment by gskjold** [comment]
This information is already available in dayplot.json where usage for the last 24hrs are stored by UTC hour. Having a "usage last hour" variable would be convenient, but it will also consume more memory (although a very small amount) which I am very careful with these days. Memory is best reserved for added features.

**Comment by kitten77** [comment]
That i can agree with you on, memory is a precious thing.

Been looking at the dayplot.json and i am not sure how i should read this. 
Today is 16.12 07:00 that would make 
i00 15.12 00:00 ? 

Should the e00 be 16.12 00:00 cause that one reads 0. 

Also been looking for the jsonprices.json which won't load in the browser for some reason, is that only being posted to the mqtt?

**Comment by gskjold** [comment]
i00 through i23 is import in UTC time for the last 24 hours. So i00 right now would be 16.01 00:00 UTC or 01:00 CET. 

For prices, the URL would be /energyprice.json
