### ISSUE TITLE
Negative current shown as positive current.

### ISSUE THREAD

**Issue by rndfm** [gskjold/AmsToMqttBridge#314]
When exporting to the grid one or more phases must have negative current.

But all phases is shown with positive current?
MQTT also shows all positive currents.

I'm trying to use the AMS as a meter for a solar inverter. And it needs to know the power/current for each phase.

![image](https://user-images.githubusercontent.com/46886958/190913041-51c2fabc-1e3a-4e35-af70-f321fb1a53cc.png)

**To Reproduce**
1. Export power on one or more phases
2. Observe no phases is shown with a negative current.

**Expected behavior**
Phases current should be negative when power is exported on that phase.

**Hardware information:**
 - Country: Denmark
 - Meter: Kamstrup 3P
 - Encryption enabled: yes
 - AMS reader: POW-K+, HAN-PORT LESER FOR KAMSTRUP STRØMMÅLER

**Relevant firmware information:**
 - Version: 2.1.7
 - MQTT:  yes
 - HAN GPIO: 
 - HAN baud and parity: 2400 8N1

**Comment by ArnieO** [comment]
There is no sign on the current data coming from the meter, so no negative current reported. Power is reported as either net Import or net Export, this is how the direction of energy flow is reported. 
So what you see is normal behavior.

**Comment by rndfm** [comment]
I'm sorry the hear that but thanks for clarifying.

I will go buy me another meter :)
