### ISSUE TITLE
ESP Vcc 

### ISSUE THREAD

**Issue by ArnieO** [gskjold/AmsToMqttBridge#32]
The unit for the figure returned by EDP.getVcc() is 1/1024 V
So to get the 'correct' voltage in V you need to divide by 1024. 
Like:
`float vccVolt = ((float)ESP.getVcc())/1024;`

**Comment by ArnieO** [comment]
In the MQTT message Vcc has six decimals while the measurement resolution is 1/1024 V.
So three decimals is sufficient / more correct - and will reduce the length of the MQTT message.

**Comment by ArnieO** [comment]
I suspect Vcc in the GUI is rounded to one decimal but presented with two decimals. I followed the GUI closely while MQTT value changed by 0,02 V but last decimal in GUI was always zero.

**Comment by gskjold** [comment]
Does not happen on any of my devices. This could be browser specific. Will change MQTT message :)

**Comment by ArnieO** [comment]
I have not yet seen the second Vcc decimal in GUI different from zero, on Safari (iPad) and on Firefox (PC).
