### ISSUE TITLE
Home Assistant updates for v2.1.9

### ISSUE THREAD

**Issue by gskjold** [gskjold/AmsToMqttBridge#320]
I am working through multiple issues here, so I thought I'd merge them into one. 

Here is the latest patch:
[esp8266.zip](https://github.com/gskjold/AmsToMqttBridge/files/9686506/esp8266.zip)
[esp32s2.zip](https://github.com/gskjold/AmsToMqttBridge/files/9686507/esp32s2.zip)
[esp32.zip](https://github.com/gskjold/AmsToMqttBridge/files/9686508/esp32.zip)

**Comment by jonthe101** [comment]
Nice! I will try it out as soon as I get some spare time 👍

**Comment by tbarnekov** [comment]
I'm seeing the MQTT error as as well. I tracked it down to the code that populates the /realtime topic in the HA mqtt handler. It's specifically the iteration of the peaks array that causes it, but I'm not sure why. If I comment the code that populates the peaks string, everything works (except the peaks of course).

**Comment by gskjold** [comment]
Thanks for the debugging, I can take a guess at the problem, here is an update:
[esp32.zip](https://github.com/gskjold/AmsToMqttBridge/files/9726109/esp32.zip)
[esp32s2.zip](https://github.com/gskjold/AmsToMqttBridge/files/9726110/esp32s2.zip)
[esp8266.zip](https://github.com/gskjold/AmsToMqttBridge/files/9726111/esp8266.zip)

**Comment by retrov** [comment]
This really helped, lots of new sensors now in HA.

**Comment by jonthe101** [comment]
Tried it out now and it's very good, I got the sensors I wanted :)
Nice work!

**Comment by gskjold** [comment]
Excellent, then this will be included in next release
