### ISSUE TITLE
Proposal for a new display of the month's three highest consumptions

### ISSUE THREAD

**Issue by eireit** [gskjold/AmsToMqttBridge#328]
Today only the average of the month's highest consumption per day is shown.
Suggest that you display this in table format and show which days have the highest consumption. Attached display used by the Oss app as an example.

![20221013_210729336_iOS](https://user-images.githubusercontent.com/79528044/195713100-e7bdcdf5-78d0-4d35-86e4-839d5fc0856c.png)

**Comment by ArnieO** [comment]
Thank you for interesting proposition!

**Comment by eireit** [comment]
Do you use the average of the five highest per month?  ea":{"x":4.9,"p":[5.62,4.49,4.72,5.16,4.61] . Is the average of the three highest (on three different days) that counts. This is relevant for Lyse and Fagne (Haugaland kraft) at least.

**Comment by ArnieO** [comment]
> Is the average of the three highest (on three different days) that counts. This is relevant for Lyse and Fagne (Haugaland kraft) at least.

This is what is calculated and displayed at the right of the "Real time consumption" line.
The number of hours to average is set in here: Configuration / Meter / Configure tariff thresholds / Average of top

My setting:
![image](https://user-images.githubusercontent.com/10295178/196001146-1f197136-100b-45f5-8256-41fbe91ea61a.png)
My current value on the "Real time consumption" line:
![image](https://user-images.githubusercontent.com/10295178/196001195-427337df-64e2-49ac-8f8b-471ed1fb2a55.png)
This means: My current average of the top 3 hours in 3 different days is 6.7, and the nest threshold level (to be avoided) is 10.

**Comment by eireit** [comment]
Thanks for the explanation.

**Comment by gskjold** [comment]
A visual presentation of peaks will be included in v2.2, but it will not be as detailed as this.
