### ISSUE TITLE
Improve ENTSO-E error handling and error reporting

### ISSUE THREAD

**Issue by gskjold** [gskjold/AmsToMqttBridge#340]
If there is a problem fetching prices, it does not retry. And there is no feedback for user. Improve feedback.

**Comment by shadowano** [comment]
Are there any known workarounds if this issue occurs? Like changing ENTSO-E settings and save?

**Comment by ArnieO** [comment]
If you restart (System/restart) it will read prices from Entso-E if available. 
The issue is that if Entso-E prices are not made available at the daily check, it will not retry until next day. 
We saw this issue earlier this week, when Entso-E had a significant delay in publishing day-ahead prices.
