### ISSUE TITLE
Will the UI show anything if data is received but keys are missing?

### ISSUE THREAD

**Issue by sirtet** [gskjold/AmsToMqttBridge#344]
Grid Company did just now enable HAN-push, but i don't have the decryption keys yet.
Should i already see a change in the UI?

Suggestion:
Show details about the HAN-Status like "no data received. 1. Check your Hardware setup 2. Check with your Grid Company if HAN-PUSH is activated" or "receiving data, but keys missing or wrong baud rate"
This will help getting started especially for people who use DIY hardware like a dev-board and are more prone to hardware-problems than someone using POW-K or so.

**Hardware information:**
 - Meter: Kamstrup Omnipower
 - Encryption enabled yes
 - AMS reader:  ESP32 

**Relevant firmware information:**
 - Version: 2.1.11
 - HAN GPIO: GPIO16
 - HAN baud and parity: 2400 8N1

**Comment by ArnieO** [comment]
If you do not have encryption keys you will not see anything in UI.
So it is a good idea to display a message like the one you propose! 👍 

You will be able to see incoming raw data by running Telnet debug (System/Debug). 
Give me a few minutes, and I'll post a "how to" on https://amsleser.no/blog

**Comment by sirtet** [comment]
Thanks, got it working.

Idea: Wouldn't it be fairly easy to output the debug data directly in the UI?
More accessible for less techy users...

**Comment by gskjold** [comment]
If you have anything specific in mind for showing debug data in UI, please elaborate. The way I see it, there is no way around a buffer, which is memory consumption we cannot afford.

**Comment by sirtet** [comment]
Well, i thought it whould take about the same resources to send data as json to the UI as it does over serial/telnet. 
So my idea was to show the same output in the UI.
But off course, i don't know about what that really takes.

**Comment by gskjold** [comment]
True in some ways, but the amount of memory needed to store and keep track of these numbers are fixed and limited. To know what have been added to the log since the last time it was fetched would require a larger buffer as one does not know how much will happen until next data poll. It may be possible to limit that memory footprint by utilizing websockets, but I have not had time to experiment with that yet.

**Comment by gskjold** [comment]
v2.2 beta out for testing now:
https://github.com/gskjold/AmsToMqttBridge/discussions/370
