### ISSUE TITLE
Show the production in money, using the ENTSO-E API

### ISSUE THREAD

**Issue by andreas1974** [gskjold/AmsToMqttBridge#346]
**Is your feature request related to a problem? Please describe.**
Could you add the value of produced (sold) electricity as well?

**Describe the solution you'd like**
Show the value in SEK, NOK or DKK just as it is done for electricity bought.

**Additional context**
![Capture](https://user-images.githubusercontent.com/998258/198333016-03b6e509-809e-4c79-9b63-98f6263b3367.JPG)

**Comment by gskjold** [comment]
I knew this one was coming :) Will implement at some point

**Comment by ArnieO** [comment]
It will surely be interesting, but will also add a layer of complexity, as the value of the exported energy will vary significantly with the individual contract with the energy company. 
Using the PV installation on my previous house as an example: I received 1,00 NOK flat for each kWh exported. Other energy companies will give you market spot price.

**Comment by andreas1974** [comment]
ArnieO: The complexity for electricity bought is also much bigger. It's common to have a flat rate price for that as well.
Perhaps you could write "Real time consumption (spot price)" and "Real time production (spot price)" to make it clear that the amounts within paratheses are just the spot prices.

In both cases (buy as well as sell) there are additional costs or incomes on each kWh bought or sold. **I'm fine with just seeing the spot price for energy bought, and did not expect to see anything else for energy sold.**

_(If you would like to make it more complex, then you would need to do that for consumption price as well.  When buying energy you need to add the transfer fee (X öre/kWh), a certificate fee and possibly some minor yearly fees (som of them per kWh others per year or month). And taxes.
When selling electricity you get a few öre/kWh for "Nätnytta" due to the fact that local production of electricity means less transports, and less strain on the net.)_

**Comment by ArnieO** [comment]
@andreas1974 
I agree, you have valid points here! Pricing model also for import is indeed complex, and varies a lot. Both between countries but also within same country, between grid companies and electricity companies (energy seller). 
Not sure if it is a good idea to change text to "Real time consumption (spot price)", as this depends on how each user sets the price multiplicator (e.g. to simulate at least VAT).

**Comment by gskjold** [comment]
v2.2 beta out for testing now:
https://github.com/gskjold/AmsToMqttBridge/discussions/370
