### ISSUE TITLE
Uptime rollover after 50 days

### ISSUE THREAD

**Issue by ArnieO** [gskjold/AmsToMqttBridge#35]
ESP uptime is direct readout of millis(), which has data type **unsigned long**, ranging from 0 to 4,294,967,295.
So it will roll over to zero after approximately 50 days.

**Comment by gskjold** [comment]
Fixed for UI.
JSON does not like uint64, so adding this as millis uptime in json is not working. Best I can come up with is using uptime in seconds. Or just accept that "up" in JSON to MQTT is rolling over.

**Comment by ArnieO** [comment]
I think the expanded number could be sent as string in the JSON. But as this timer is not synchronized with anything I do not really see the relevance of millisecond resolution.
So I agree with you: Uptime in seconds should be fine.

**Comment by gskjold** [comment]
Agreed, milliseconds resolution is excessive in this case. It would also require the receiving part to support uint64.

Reducing resolution on "up" field to seconds and announcing this as an API change in next release.
