### ISSUE TITLE
add support to send reboot command over ssh or http request 

### ISSUE THREAD

**Issue by CHHE-ledtec** [gskjold/AmsToMqttBridge#356]
**Is your feature request related to a problem? Please describe.**
webui not accessble  . units is in remote location

need to reboot system probebly remote or on site.

Request:
add support to send reboot command over ssh or http request  or other possible way

**Comment by gskjold** [comment]
If webui is not accessible then it wouldn't be possible to reboot over http.
But if you want to try, run POST /restart which in return should redirect you to GET /restart-wait which will do the actual reboot
