### ISSUE TITLE
Typo in last version of HanToJson.cpp.

### ISSUE THREAD

**Issue by atlej68** [gskjold/AmsToMqttBridge#36]
......
 data["QO"]      = hanReader.getInt(             (int)Aidon_List3PhaseIT::ReactiveExportPower);
 data["I1"]      = ((double) hanReader.getInt(   (int)Aidon_List3PhaseIT::CurrentL1)) / 10;
 data["I1"]      = 0;
........
Last line shall be 
 data["I2"]      = 0;

**Comment by gskjold** [comment]
Thanks! a bit of a copy/paste error
