### ISSUE TITLE
Which values are persisted and which are reset during reboot?

### ISSUE THREAD

**Issue by shadowano** [gskjold/AmsToMqttBridge#360]
**Describe your problem**
What values are persisted and which one are reset during a reboot? I see that the current hour kwh is reset during reboot. Are there other values that are persisted, and will not be lost?

I'm interested in knowing which sensors in Home Assistant I can use to build up the workflow I want, without having blank values, or values being reset if the device reboots.

**Hardware information:**
Country: Norway
Meter: Aidon
Encryption enabled no
AMS reader: Pow-U, ESP32-S2
M-bus adapter (if applicable):

**Relevant firmware information:**
Version: 2.1.13
MQTT: yes
MQTT payload type: Home Assistant
HAN GPIO: GPIO16
HAN baud and parity: 2400 8E1
Temperature sensors:
ENTSO-E API enabled: yes

**Comment by gskjold** [comment]
I'm not sure if you are talking about persist flag on MQTT or data being persisted on device. Peaks, month max and threshold are the only ones that are persisted on the device. All other sensors are realtime data which would not make sense to persist. In HA mode, no MQTT topics have the persist flag.
