### ISSUE TITLE
In "Energy used last month" number not showing

### ISSUE THREAD

**Issue by putte64** [gskjold/AmsToMqttBridge#367]
**Describe the bug**
Number in the diagram is displayed with same color as the bar.

**Expected behavior**
Number should be white when displaying inside the bar.

**Screenshots**
![WrongColor](https://user-images.githubusercontent.com/2694088/204391473-e70bc65f-bc13-4feb-a134-bbb6cdbcfa7b.png)
![NumberDisappeared](https://user-images.githubusercontent.com/2694088/204391475-644d8248-1de2-4daa-81df-bdf1926bb5ed.png)

**Hardware information:**
 - Country: Norway
 - Meter:  Aidon
 - Encryption enabled [yes/no]
 - AMS reader: ESP32

**Relevant firmware information:**
 - Version: 2.1.14
  - ENTSO-E API enabled: yes

**Comment by gskjold** [comment]
Thanks for reporting this bug. I think this is technically a Google Charts bug, which is no longer in use in the upcoming v2.2. It will be released for testing soon
