### ISSUE TITLE
additional baud rate for smart meters with infrared interface

### ISSUE THREAD

**Issue by tqma1** [gskjold/AmsToMqttBridge#373]
i want to use it with the Siemens TD-3511 smart meter which has an infrared interface which uses the following parameters:
300 baud, 7 bits, 1 stop bit and even parity
can you please implement this?

Best regards,
Thomas

**Comment by gskjold** [comment]
Added in release that will be release any minute now. No guarantees it works with your setup though, not heard of any that use it with IR. But I see it uses IEC62056-21, so there is a possibility

**Comment by ArnieO** [comment]
@tqma1 It will be interesting to know if the firmware works on an optical interface - please get back and give us an update!

**Comment by gskjold** [comment]
http://www.mitterbaur.at/amis-leser.html

A quick skim through the source code, I see some serial.write, so it may need to request the data from the meter

**Comment by ArnieO** [comment]
> So it will not work with my smart meter but great work from you!

That is right. This firmware will (currently) only work on meters configured for "Data push".
