### ISSUE TITLE
It seems that nordpool and entso has a small difference in prices (NO3) even with a mva factor of 1.25 in multiplier added

### ISSUE THREAD

**Issue by Ontrackx** [gskjold/AmsToMqttBridge#388]
Nordpool 1.70NOK
ENTSO      1.94NOK

Checked my power delivery company vibb, and  vibb says 1,66
 at 10:00

**Comment by gskjold** [comment]
Indeed, all system prices are given in EUR/MWh, what number you end up with in NOK depends on exchange rate you use. Would be good to be in sync, but I have no idea what strategy they use to choose exchange rate.

**Comment by ArnieO** [comment]
But that difference is too much to be due to exchange rate?

**Comment by tronde-ams** [comment]
The price published by Nordpool and Entso-e for NO3 is 129.7 EUR /MWh.
Did the interface fetch correct prices?

![nordpool](https://user-images.githubusercontent.com/97398751/208263451-7e458128-caeb-4d11-8185-1f359f892808.jpg)
![entsoe](https://user-images.githubusercontent.com/97398751/208263452-fd9c6045-8998-473d-9180-ddcbd1ca6112.jpg)

**Comment by gskjold** [comment]
I agree the different sounds a bit much, I guess it probably is something else then.

**Comment by ArnieO** [comment]
Our price data seems correct, but the exchange rate for conversion to local currency seems to be different compared to Nordpool. 
@Ontrackx : Could you elaborate on your findings? Your price difference seems not explainable by exchange rate differences. (You get a JSON with prices by atting /energyprices.json to your URL):
![image](https://user-images.githubusercontent.com/10295178/208390792-463e4816-bac5-4f54-a6df-210a26f7b695.png)

![image](https://user-images.githubusercontent.com/10295178/208390001-92285733-920a-4969-a6e7-a73853e3a03f.png)

**Comment by gskjold** [comment]
Closed due to inactivity
