### ISSUE TITLE
ENTSO-E API configuring option

### ISSUE THREAD

**Issue by kitten77** [gskjold/AmsToMqttBridge#391]
Option for configure the ENTSO-E API disappears if you enter one of the sub menu choices

**To Reproduce**
open configuration menu enter Meter
or any other option, and ENTSO-E API is missing
go back to main page and ENTSO-E API is back as a option 

 - ENTSO-E API enabled: [yes]

**Comment by henriklund** [comment]
Hi there,

Please look here [#372](https://github.com/gskjold/AmsToMqttBridge/issues/372)

**Comment by kitten77** [comment]
Thanks haven't looked at the already opened reports :)
