### ISSUE TITLE
No login

### ISSUE THREAD

**Issue by skjeldgaard** [gskjold/AmsToMqttBridge#392]
I have updated the security settings, with username and password.
When accessing the device you are not prompted for at login, neither is a url for login provided in documentation, leaving the device UI impossible to access.

**Comment by ArnieO** [comment]
Which firmware version is this? 
Could it be your browser that blocks popups?

**Comment by skjeldgaard** [comment]
Running Edge on WorkPC - can't get it to work.... Works in Chrome.
Maybe leave note in documentation :)
thx!

**Comment by skjeldgaard** [comment]
Not really sure, not able to get it to open the login popup - might be to
do with some settings being controlled by my organization.

best regardds

**Comment by ArnieO** [comment]
Ah, ok - that makes sense.
