### ISSUE TITLE
WEB GUI responds incorrectly to net power export.

### ISSUE THREAD

**Issue by ArnieO** [gskjold/AmsToMqttBridge#41]
When my solar panel kicks in and I have net power export the GUI signals HAN error (red indicator), and no export data is indicated:
![image](https://user-images.githubusercontent.com/10295178/75144118-9df14600-56f6-11ea-948a-b0432f736f14.png)
MQTT messages are still flowing, and my Node-Red implementation shows export power correctly.
As soon as net import is back, the red HAN light goes green, and the GUI behaves correctly, showing imported power.

**Comment by gskjold** [comment]
https://github.com/gskjold/AmsToMqttBridge/commit/9671e1eba334a1d7b052175086f43c2f602508a7

Fixed in this commit. Maybe I also fixed the Vcc precision?

**Comment by ArnieO** [comment]
Great - it works correctly now! For the Vcc second decimal we will have to wait and see, the small voltage spikes occur very randomly. 
![image](https://user-images.githubusercontent.com/10295178/75153658-3940e600-570c-11ea-8962-1400e46a0c25.png)
