### ISSUE TITLE
Meter timestamp / daylight saving time

### ISSUE THREAD

**Issue by ArnieO** [gskjold/AmsToMqttBridge#43]
From my Kamstrup meter I receive at 11:19 the timestamp 1582715950 in MQTT, which according to https://time.is/Unix_time_converter translates to:
**Wed Feb 26 2020 12:19:10 UTC+0100 (Central European Standard Time)**

Which seems to be 1 hour off. 

According to https://github.com/gskjold/AmsToMqttBridge/blob/master/doc/NVE_Info_kunder_HANgrensesnitt.pdf
the timestamp shall be local time in Norway, taking into account daylight saving time (DST).
But the timestamp from my meter seems to be at DST already?
- Is the MQTT timestamp raw data from the meter?
- Do users of other meters / meter brands see the same?

**Comment by gskjold** [comment]
The meters does not send data as unixtime, but as a set of numbers representing the date and time in a predefined timezone. This is in turn converted to unixtime in the code, but does not take timezone into account. If effect the date and time from the meter is interpreted as UTC time which is incorrect.
