### ISSUE TITLE
latest version fails to boot 

### ISSUE THREAD

**Issue by atlej68** [gskjold/AmsToMqttBridge#58]
feather esp32:  
The latest version fails on boot if complied with  -D DEBUG_MODE=1.  
-Tested both with clean flash and existing configuration.
Version 1.1.2 is ok.

Trace:
------------------------------------------------------------------
rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0018,len:4
load:0x3fff001c,len:1044
load:0x40078000,len:8896
load:0x40080400,len:5828
entry 0x400806ac
/home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/freertos/queue.c:1442 (xQueueGenericReceive)- assert failed!
abort() was called at PC 0x40088d55 on core 1

Backtrace: 0x4008c920:0x3ffb1ca0 0x4008cb51:0x3ffb1cc0 0x40088d55:0x3ffb1ce0 0x4015480e:0x3ffb1d20 0x40154aea:0x3ffb1d40 0x40143228:0x3ffb1d60 0x40143291:0x3ffb1d80 0x4013ecea:0x3ffb1da0 0x4013d714:0x3ffb1dc0 0x4014218c:0x3ffb1e00 0x4015efab:0x3ffb1e20 0x400e4dc5:0x3ffb1e60 0x400e4fab:0x3ffb1e80 0x400d71c2:0x3ffb1eb0 0x400f00cb:0x3ffb1fb0 0x40089069:0x3ffb1fd0

Rebooting...
ets Jun  8 2016 00:22:57

**Comment by gskjold** [comment]
Turns out I have not tested on ESP32 after I added RemoteDebug. It does not like to activate Telnet when WiFi is not connected. Moved around some code. Fixed in v1.2.1
