### ISSUE TITLE
Bug in MQTT raw values

### ISSUE THREAD

**Issue by jnrksv** [gskjold/AmsToMqttBridge#59]
Seems to be a bug in the raw values.
The "vcc" has the value from the "temp" and "temp" header is missing. I think you see this more clearly in the attached screenshot containing both json and raw.

![ams2mqtt-json-raw](https://user-images.githubusercontent.com/24974747/78879827-be7e2100-7a54-11ea-8d2c-47efc5bfa5ca.PNG)

I'm running ams2mqtt-d1mini-1.2.1.bin, by the way. Had the same bug in 1.2.0. Haven't tested any other releases.

**Comment by gskjold** [comment]
Typo in the code. Fixed in v1.2.2
