### ISSUE TITLE
Negative current

### ISSUE THREAD

**Issue by stenjo** [gskjold/AmsToMqttBridge#64]
When production and exporting energy the current value is displayed incorrectly. 
![DCD9D93A-5408-41A5-96A8-479EC6235821](https://user-images.githubusercontent.com/668722/79454620-d709b080-7feb-11ea-88fe-bc03dac0bf93.png)

**Comment by stenjo** [comment]
Trying to compile a local version to test this. Will soon be back with test results.
![ams_negative_current](https://user-images.githubusercontent.com/668722/79554390-45a74680-809e-11ea-9888-08d5fe73dc74.PNG)

**Comment by gskjold** [comment]
Thanks, while your PR probably fix it, I can see a number of other things wrong with the surrounding code that will need to be addressed as well to avoid future problems. I think the best way will be to take the code apart and do type casting for each of the types. I have some ideas on best approach, I'll see if I can whip up a quick solution later.

**Comment by stenjo** [comment]
Seems like the fix removed the bug.
![Capture](https://user-images.githubusercontent.com/668722/79583187-122fe080-80cd-11ea-842b-ef925484552e.PNG)

**Comment by stenjo** [comment]
![654B059B-2B79-4AD5-ADAA-11835338A1F6](https://user-images.githubusercontent.com/668722/79632716-6ab0bd80-8161-11ea-811c-c7451cf8fdd1.jpeg)
Still looks good.

**Comment by gskjold** [comment]
I did some work on it this morning where I corrected the conversion for int8, int16 and uint32. Please see this branch: https://github.com/gskjold/AmsToMqttBridge/tree/dev-v1.2.3
I've run a number of tests on the code and it gives correct results.

**Comment by stenjo** [comment]
Initial test looks good with your revised dev-v1.2.3
![Capture](https://user-images.githubusercontent.com/668722/79687030-bbe5ad80-8244-11ea-8efd-7459864b73c2.PNG)

**Comment by gskjold** [comment]
Great! I also had it running in parallel with 1.2.2, can't see it changed anything on the other values either.
