### ISSUE TITLE
I2 calculation on Aidon meters is not correct when exporting

### ISSUE THREAD

**Issue by Allram** [gskjold/AmsToMqttBridge#82]
The I2 calculation on the Aidon meters is not correct when exporting power.

It says I have:
I1 -21.3A
I2 37.37A
I3 -16.3A

That is not correct as I have 2 Solar inverters that are connected: L1-L2 and L2-L3. So I2 should have had the most exported Ampers.

When importing power it is correct :-)

**Comment by gskjold** [comment]
Thanks, I can see the error. Will fix on a rainy day :)

**Comment by gskjold** [comment]
Did a quick commit to master with a quick fix I think should work

**Comment by Allram** [comment]
Will make a build and test early next week, thanks 👍

**Comment by Allram** [comment]
Works as a charm!
